packages:
  - 'packages/*'

catalogs:
  astro:
    "@hebilicious/cssforge": "jsr:^0.4.1"
    "astro": "^5.15.1"
    "@astrojs/vue": "^5.1.1"
    "@vite-pwa/astro": "^1.1.1"
    "@vueuse/core": "^14.0.0"
    "vue": "^3.5.22"
    "rehype-autolink-headings": "^7.1.0"
    "rehype-slug": "^6.0.0"
    "@microflash/rehype-figure": "^2.1.4"
  nuxt:
    "@nuxt/devtools": "latest"
    "@nuxt/image": "1.0.0-rc.1"
    "@types/node": "^18"
    "@unocss/nuxt": "^0.53.1"
    "@unocss/transformer-directives": "^0.53.1"
    "@vite-pwa/assets-generator": "^0.0.2"
    "@vite-pwa/nuxt": "^0.1.0"
    "@vue/test-utils": "^2.3.2"
    "@vueuse/nuxt": "^10.1.2"
    "jsdom": "^22.1.0"
    "nuxt": "^3.5.2"
    "postcss": "^8.4.24"
    "postcss-100vh-fix": "^1.0.2"
    "postcss-nested": "^6.0.1"
    "postcss-viewport-height-correction": "^1.1.1"
    "vitest": "^0.32.0"
    "wrangler": "^3.1.0"
    "@unocss/reset": "^0.53.1"
    "@vueuse/core": "^10.1.2"
    