/** This file is automatically generated by Flamme. Do not edit. */

export * from '@flamme/runtime'

export const COMPILER_VERSION = '0.0.0'
export const RUNTIME_VERSION = '0.0.0'

/** Key fields per type, as resolved from the schema and the config. */
export const cacheKeys: Readonly<Record<string, readonly string[]>> = {
  "Block": ["id"],
  "Favourite": ["slug"],
  "Note": ["id"],
  "Post": ["slug"],
  "Repository": ["name"],
  "Role": ["id"],
  "School": ["id"],
  "Shelf": ["slug"],
  "Site": ["name"],
}

export const defaultKeys: readonly string[] = ["id"]
