// Generated by scripts/derive-palette.mjs. Do not edit by hand.
// Run `node scripts/derive-palette.mjs` after changing an anchor.

export const neutrals = {
	"0": "#ffffff",
	"50": "#f7f6f3",
	"100": "#eceae5",
	"200": "#dbd8d1",
	"300": "#b8b4ab",
	"400": "#8d897f",
	"500": "#6a665e",
	"600": "#4c4943",
	"700": "#35322e",
	"800": "#22201d",
	"900": "#151412",
	"950": "#0a0a09"
} as const

export const accents = {
	"aqua": {
		"100": "#87ffff",
		"200": "#6ce8e8",
		"300": "#59cccc",
		"400": "#40abab",
		"500": "#278a8b",
		"600": "#076b6c",
		"700": "#045050",
		"800": "#023536",
		"900": "#011d1d",
		"950": "#010a0a"
	},
	"frost": {
		"100": "#bff2ff",
		"200": "#90dff2",
		"300": "#7ac5d6",
		"400": "#61a4b4",
		"500": "#488593",
		"600": "#306673",
		"700": "#1b4d57",
		"800": "#04343d",
		"900": "#001c23",
		"950": "#00090d"
	},
	"peri": {
		"100": "#e6e5fe",
		"200": "#cfcafe",
		"300": "#b5b0e6",
		"400": "#9692c2",
		"500": "#79749f",
		"600": "#5c587e",
		"700": "#444061",
		"800": "#2d2945",
		"900": "#18142c",
		"950": "#070416"
	},
	"pink": {
		"100": "#ffdded",
		"200": "#fabcda",
		"300": "#e1a1c1",
		"400": "#bf84a1",
		"500": "#9c6882",
		"600": "#7b4d65",
		"700": "#5e364b",
		"800": "#432133",
		"900": "#290c1d",
		"950": "#14010a"
	},
	"rose": {
		"100": "#fedfe2",
		"200": "#febdc5",
		"300": "#f09ca8",
		"400": "#d17b88",
		"500": "#ad606c",
		"600": "#894651",
		"700": "#6b2f3a",
		"800": "#4e1924",
		"900": "#320510",
		"950": "#160004"
	}
} as const

export type AccentName = keyof typeof accents
export type NeutralStep = keyof typeof neutrals
