/**
 * Generated by scripts/build-content.ts. Do not edit.
 *
 * Every block of every article, each carrying the footnotes it cites, plus the
 * data the Library and the Experience page read. Typed by src/content.ts.
 */

export const site = {
	"name": "Emmanuel",
	"tagline": "Software engineer. Notes on the tools, the science and the history.",
	"date": "2026-09-20",
	"sections": [
		{
			"slug": "modules",
			"label": "Nuxt & Vue modules",
			"repositories": [
				{
					"name": "form-actions-nuxt",
					"description": "Nuxt Module that implements Form Actions",
					"language": "TypeScript",
					"url": "https://github.com/Hebilicious/form-actions-nuxt",
					"homepage": "https://form-actions-nuxt.pages.dev/",
					"archived": false,
					"category": "modules",
					"stars": null
				},
				{
					"name": "vue-query-nuxt",
					"description": "A lightweight, 0 config Nuxt Module for Vue Query.",
					"language": "TypeScript",
					"url": "https://github.com/Hebilicious/vue-query-nuxt",
					"homepage": null,
					"archived": false,
					"category": "modules",
					"stars": null
				},
				{
					"name": "server-block-nuxt",
					"description": "Use <server> tags in your Nuxt pages components",
					"language": "TypeScript",
					"url": "https://github.com/Hebilicious/server-block-nuxt",
					"homepage": null,
					"archived": false,
					"category": "modules",
					"stars": null
				},
				{
					"name": "dom-snapshot-nuxt",
					"description": "DOM Snapshot module for Nuxt",
					"language": "TypeScript",
					"url": "https://github.com/Hebilicious/dom-snapshot-nuxt",
					"homepage": null,
					"archived": false,
					"category": "modules",
					"stars": null
				},
				{
					"name": "vue-switch-match",
					"description": "Switch Match components for Vue and Nuxt.",
					"language": "TypeScript",
					"url": "https://github.com/Hebilicious/vue-switch-match",
					"homepage": null,
					"archived": false,
					"category": "modules",
					"stars": null
				},
				{
					"name": "nuxtpress",
					"description": "A nuxt module to use markdown files as pages",
					"language": "TypeScript",
					"url": "https://github.com/Hebilicious/nuxtpress",
					"homepage": null,
					"archived": false,
					"category": "modules",
					"stars": null
				},
				{
					"name": "authjs-nuxt",
					"description": "AuthJS edge-compatible authentication Nuxt module.",
					"language": "TypeScript",
					"url": "https://github.com/Hebilicious/authjs-nuxt",
					"homepage": "https://authjs-nuxt.pages.dev/",
					"archived": true,
					"category": "modules",
					"stars": null
				}
			]
		},
		{
			"slug": "tooling",
			"label": "Tooling & templates",
			"repositories": [
				{
					"name": "cssforge",
					"description": "Generate CSS variables from design tokens.",
					"language": "TypeScript",
					"url": "https://github.com/Hebilicious/cssforge",
					"homepage": "https://jsr.io/@hebilicious/cssforge",
					"archived": false,
					"category": "tooling",
					"stars": null
				},
				{
					"name": "nuxt-module-template",
					"description": "A template for Nuxt Modules with Pnpm and Bun",
					"language": "TypeScript",
					"url": "https://github.com/Hebilicious/nuxt-module-template",
					"homepage": null,
					"archived": false,
					"category": "tooling",
					"stars": null
				},
				{
					"name": "reproduire",
					"description": "Github Action that comments on incomplete issues.",
					"language": "JavaScript",
					"url": "https://github.com/Hebilicious/reproduire",
					"homepage": null,
					"archived": false,
					"category": "tooling",
					"stars": null
				},
				{
					"name": "rollup-plugin-web-worker",
					"description": "Rollup plugin that loads web worker in a dedicated chunk.",
					"language": "TypeScript",
					"url": "https://github.com/Hebilicious/rollup-plugin-web-worker",
					"homepage": null,
					"archived": false,
					"category": "tooling",
					"stars": null
				},
				{
					"name": "serverless-esbuild-template",
					"description": "This is a template repository to get you started really quickly with the serverless framework and typescript.",
					"language": "TypeScript",
					"url": "https://github.com/Hebilicious/serverless-esbuild-template",
					"homepage": null,
					"archived": false,
					"category": "tooling",
					"stars": null
				},
				{
					"name": "ungraphql-parse-info",
					"description": "An ESM, JSR published, edge compatible GraphQL info parser based on graphql-parse-resolve-info",
					"language": "TypeScript",
					"url": "https://github.com/Hebilicious/ungraphql-parse-info",
					"homepage": "https://jsr.io/@hebilicious/ungraphql-parse-info",
					"archived": false,
					"category": "tooling",
					"stars": null
				},
				{
					"name": "graphql-crawler",
					"description": "Crawl URLs and generate Sitemaps",
					"language": "TypeScript",
					"url": "https://github.com/Hebilicious/graphql-crawler",
					"homepage": null,
					"archived": false,
					"category": "tooling",
					"stars": null
				}
			]
		},
		{
			"slug": "chain",
			"label": "Chain & cryptography",
			"repositories": [
				{
					"name": "mnemonic-to-private-key",
					"description": "Convert a mnemonic phrase to a private key",
					"language": "JavaScript",
					"url": "https://github.com/Hebilicious/mnemonic-to-private-key",
					"homepage": null,
					"archived": false,
					"category": "chain",
					"stars": null
				},
				{
					"name": "plutus-guide",
					"description": "A guide for Plutus",
					"language": "Dockerfile",
					"url": "https://github.com/Hebilicious/plutus-guide",
					"homepage": null,
					"archived": false,
					"category": "chain",
					"stars": null
				},
				{
					"name": "nats-ml",
					"description": "OCaml bindings for NATS",
					"language": "OCaml",
					"url": "https://github.com/Hebilicious/nats-ml",
					"homepage": null,
					"archived": false,
					"category": "chain",
					"stars": null
				},
				{
					"name": "spacebudz-identity",
					"description": "Identity verification for SpaceBudz",
					"language": "Haskell",
					"url": "https://github.com/Hebilicious/spacebudz-identity",
					"homepage": null,
					"archived": false,
					"category": "chain",
					"stars": null
				}
			]
		}
	]
}

export const shelves = site.sections

export const posts = [
	{
		"slug": "hyper-anabasis",
		"title": "How Europe Falters When Philosophy Abandons Fundamental Science.",
		"description": "An exploration of how the relationship between philosophy and fundamental science has shaped European civilization through cycles of integration and schism.",
		"date": "2025-10-25",
		"tags": [
			"philosophy",
			"science",
			"history",
			"europe",
			"enlightenment"
		],
		"notes": [
			{
				"id": "fn-1",
				"number": 1,
				"html": "<p>While the inscription is widely cited, its historical accuracy is debated. The earliest mentions appear centuries after Plato’s death. <a href=\"https://mathshistory.st-andrews.ac.uk/Biographies/Plato/\">University of St Andrews, School of Mathematics and Statistics</a></p>",
				"text": "While the inscription is widely cited, its historical accuracy is debated. The earliest mentions appear centuries after Plato’s death. University of St Andrews, School of Mathematics and Statistics"
			},
			{
				"id": "fn-2",
				"number": 2,
				"html": "<p>See Aristotle’s collected works, available online through <a href=\"http://classics.mit.edu/Aristotle/physics.html\">The Internet Classics Archive by MIT</a>.</p>",
				"text": "See Aristotle’s collected works, available online through The Internet Classics Archive by MIT."
			},
			{
				"id": "fn-3",
				"number": 3,
				"html": "<p>The closing of the Academy is a significant marker. See <a href=\"https://www.oxfordhandbooks.com/view/10.1093/oxfordhb/9780199935321.001.0001/oxfordhb-9780199935321-e-56\">Struck, P. T. (2014). <em>The Closing of the Neoplatonic Academy at Athens</em>. Oxford Handbooks Online.</a></p>",
				"text": "The closing of the Academy is a significant marker. See Struck, P. T. (2014). The Closing of the Neoplatonic Academy at Athens. Oxford Handbooks Online."
			},
			{
				"id": "fn-4",
				"number": 4,
				"html": "<p>The concept of philosophy as the \"handmaiden of theology\" (ancilla theologiae) was a guiding principle for many medieval thinkers, most famously Thomas Aquinas. <a href=\"https://faculty.fordham.edu/klima/ancilla.htm\">Boston University, \"Ancilla Theologiae\"</a></p>",
				"text": "The concept of philosophy as the \"handmaiden of theology\" (ancilla theologiae) was a guiding principle for many medieval thinkers, most famously Thomas Aquinas. Boston University, \"Ancilla Theologiae\""
			},
			{
				"id": "fn-5",
				"number": 5,
				"html": "<p>Leonardo’s anatomical studies were extensive and often conducted in secret due to societal and religious proscriptions. <a href=\"https://www.rct.uk/collection/publications/leonardo-da-vinci-the-mechanics-of-man\">\"Leonardo da Vinci: the mechanics of man\", Royal Collection Trust</a>.</p>",
				"text": "Leonardo’s anatomical studies were extensive and often conducted in secret due to societal and religious proscriptions. \"Leonardo da Vinci: the mechanics of man\", Royal Collection Trust."
			},
			{
				"id": "fn-6",
				"number": 6,
				"html": "<p>This interpretation was famously proposed by Dr. Frank Lynn Meshberger in the Journal of the American Medical Association. <a href=\"https://www.semanticscholar.org/paper/An-interpretation-of-Michelangelo%27s-Creation-of-on-Meshberger/4200f3a2c8b63940469bd5a408911bc9178afdf5\">Meshberger, F. L. (1990). \"An interpretation of Michelangelo’s Creation of Adam based on neuroanatomy\". JAMA, 264(14), 1837-1841.</a></p>",
				"text": "This interpretation was famously proposed by Dr. Frank Lynn Meshberger in the Journal of the American Medical Association. Meshberger, F. L. (1990). \"An interpretation of Michelangelo’s Creation of Adam based on neuroanatomy\". JAMA, 264(14), 1837-1841."
			},
			{
				"id": "fn-7",
				"number": 7,
				"html": "<p>The \"Galileo Affair\" is a well-documented historical event. For a summary of primary sources, see <a href=\"https://famous-trials.com/galileotrial/1014-home\">\"Famous Trials\" by Professor Douglas O. Linder</a>.</p>",
				"text": "The \"Galileo Affair\" is a well-documented historical event. For a summary of primary sources, see \"Famous Trials\" by Professor Douglas O. Linder."
			},
			{
				"id": "fn-8",
				"number": 8,
				"html": "<p>Isaac Newton’s <strong>Philosophiæ Naturalis Principia Mathematica</strong> (1687) is a cornerstone of modern science. A digitized version is available at the <a href=\"https://cudl.lib.cam.ac.uk/view/PR-ADV-B-00039-00001/1\">Cambridge University Library</a>.</p>",
				"text": "Isaac Newton’s Philosophiæ Naturalis Principia Mathematica (1687) is a cornerstone of modern science. A digitized version is available at the Cambridge University Library."
			},
			{
				"id": "fn-9",
				"number": 9,
				"html": "<p>Diderot’s <strong>Encyclopédie, ou dictionnaire raisonné des sciences, des arts et des métiers</strong> (1751-1772) was a seminal work of the Enlightenment. See the online version hosted by the <a href=\"https://gallica.bnf.fr/ark:/12148/bpt6k50534p/f2.item.r=encyclopedie.langEN\">Bibliothèque Nationale de France</a>.</p>",
				"text": "Diderot’s Encyclopédie, ou dictionnaire raisonné des sciences, des arts et des métiers (1751-1772) was a seminal work of the Enlightenment. See the online version hosted by the Bibliothèque Nationale de France."
			},
			{
				"id": "fn-10",
				"number": 10,
				"html": "<p>Adam Smith’s <strong>An Inquiry into the Nature and Causes of the Wealth of Nations</strong> (1776) is a foundational text in classical economics. See the version at the <a href=\"https://www.econlib.org/library/Smith/smWN.html\">Online Library of Liberty</a>.</p>",
				"text": "Adam Smith’s An Inquiry into the Nature and Causes of the Wealth of Nations (1776) is a foundational text in classical economics. See the version at the Online Library of Liberty."
			},
			{
				"id": "fn-11",
				"number": 11,
				"html": "<p>The phrase \"Sapere aude\" (\"Dare to know\") was used by Immanuel Kant in his 1784 essay <a href=\"https://en.wikipedia.org/wiki/What_Is_Enlightenment%3F\">\"Answering the Question: What Is Enlightenment?\"</a>.</p>",
				"text": "The phrase \"Sapere aude\" (\"Dare to know\") was used by Immanuel Kant in his 1784 essay \"Answering the Question: What Is Enlightenment?\"."
			},
			{
				"id": "fn-12",
				"number": 12,
				"html": "<p>The EU’s policy on GMOs is guided by the precautionary principle. See the <a href=\"https://www.efsa.europa.eu/en/topics/topic/gmo\">EU’s official page on the topic</a>.</p>",
				"text": "The EU’s policy on GMOs is guided by the precautionary principle. See the EU’s official page on the topic."
			},
			{
				"id": "fn-13",
				"number": 13,
				"html": "<p>For a deeper dive into the topic: <a href=\"https://www.youtube.com/watch?v=7TmcXYp8xu4\">Are GMOs Good or Bad? Genetic Engineering &#x26; Our Food, Kurzgesagt – In a Nutshell</a></p>",
				"text": "For a deeper dive into the topic: Are GMOs Good or Bad? Genetic Engineering & Our Food, Kurzgesagt – In a Nutshell"
			},
			{
				"id": "fn-14",
				"number": 14,
				"html": "<p><a href=\"https://news.stanford.edu/stories/2015/05/stanford-study-on-brain-waves-shows-how-different-teaching-methods-affect-reading-development\">Stanford study on brain waves shows how different teaching methods affect reading development</a>; <a href=\"https://www.sciencedirect.com/science/article/pii/S0093934X15000772\">Hemispheric specialization for visual words is shaped by attention to sublexical units during initial learning</a>.</p>",
				"text": "Stanford study on brain waves shows how different teaching methods affect reading development; Hemispheric specialization for visual words is shaped by attention to sublexical units during initial learning."
			},
			{
				"id": "fn-15",
				"number": 15,
				"html": "<p>Adult skills in literacy and numeracy declining or stagnating in most OECD countries <a href=\"https://www.oecd.org/en/about/news/press-releases/2024/12/adult-skills-in-literacy-and-numeracy-declining-or-stagnating-in-most-oecd-countries.html\">OECD</a></p>",
				"text": "Adult skills in literacy and numeracy declining or stagnating in most OECD countries OECD"
			},
			{
				"id": "fn-16",
				"number": 16,
				"html": "<p>Germany’s <strong>Energiewende</strong> has led to a paradoxical increase in coal use. For a comparison of CO2 intensity, looking at 5y historical data, Germany has emitted 14.9x more CO₂ than France. <a href=\"https://app.electricitymaps.com/map/zone/FR/5y/monthly\">Germany (283g CO₂eq/kWh)</a>, <a href=\"https://app.electricitymaps.com/map/zone/FR/5y/monthly\">France (19g CO₂eq/kWh)</a>.</p>",
				"text": "Germany’s Energiewende has led to a paradoxical increase in coal use. For a comparison of CO2 intensity, looking at 5y historical data, Germany has emitted 14.9x more CO₂ than France. Germany (283g CO₂eq/kWh), France (19g CO₂eq/kWh)."
			},
			{
				"id": "fn-17",
				"number": 17,
				"html": "<p>\"Anabasis\" is a Greek term meaning \"a journey upward.\" \"Hyper Anabasis\" suggests a great ascent beyond current limitations.</p>",
				"text": "\"Anabasis\" is a Greek term meaning \"a journey upward.\" \"Hyper Anabasis\" suggests a great ascent beyond current limitations."
			}
		],
		"blocks": [
			{
				"id": "b1",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>European civilization’s intellectual, political, and material progress has always depended on the integration of its philosophical thought with its fundamental science; its mathematical, physical, and biological understanding of reality. When these two domains are unified, Europe thrives. When they are in schism, with philosophy detached from its empirical anchor, Europe falters and declines.</p>",
				"text": "European civilization’s intellectual, political, and material progress has always depended on the integration of its philosophical thought with its fundamental science; its mathematical, physical, and biological understanding of reality. When these two domains are unified, Europe thrives. When they are in schism, with philosophy detached from its empirical anchor, Europe falters and declines.",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b2",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>This recurring pattern of synthesis and divergence can be traced through four distinct phases of Western history.</p>",
				"text": "This recurring pattern of synthesis and divergence can be traced through four distinct phases of Western history.",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b3",
				"kind": "heading",
				"depth": 2,
				"html": "<h2>I. The Classical Integration</h2>",
				"text": "I. The Classical Integration",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b4",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p><em>c. 600 BC – c. 529 AD</em></p>",
				"text": "c. 600 BC – c. 529 AD",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b5",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>In the classical world, no meaningful distinction existed between the philosopher and the scientist. They were unified in the pursuit of <em>logos</em> (reason) and <em>kosmos</em> (order). To be a \"thinker\" was, by definition, to be an investigator of reality at its most fundamental level. This synergy created a civilization that produced foundational insights in mathematics, politics, and ethics.</p>",
				"text": "In the classical world, no meaningful distinction existed between the philosopher and the scientist. They were unified in the pursuit of logos (reason) and kosmos (order). To be a \"thinker\" was, by definition, to be an investigator of reality at its most fundamental level. This synergy created a civilization that produced foundational insights in mathematics, politics, and ethics.",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b6",
				"kind": "heading",
				"depth": 3,
				"html": "<h3>Plato and the Academy (c. 428–348 BC)</h3>",
				"text": "Plato and the Academy (c. 428–348 BC)",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b7",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>The philosopher Plato provides a key example. His Academy in Athens, the model for all future European universities, was built on this integration. The inscription at its entrance, though possibly legendary, captures this spirit perfectly:<sup><a href=\"#user-content-fn-1\" id=\"user-content-fnref-1\" data-footnote-ref aria-describedby=\"footnote-label\">1</a></sup></p>",
				"text": "The philosopher Plato provides a key example. His Academy in Athens, the model for all future European universities, was built on this integration. The inscription at its entrance, though possibly legendary, captures this spirit perfectly:",
				"noteIds": [
					"fn-1"
				],
				"image": null,
				"caption": null
			},
			{
				"id": "b8",
				"kind": "quote",
				"depth": 0,
				"html": "<blockquote>\n<p>\"Let no one ignorant of geometry enter here.\"</p>\n</blockquote>",
				"text": "\"Let no one ignorant of geometry enter here.\"",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b9",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>Plato’s \"Theory of Forms\" argues that the physical world is a mere shadow of a perfect, eternal world of \"Forms.\" The only way to perceive this true reality was through pure reason, and the highest, most rigorous form of this reason was <strong>mathematics</strong>. For Plato, geometry was the key to unlocking a higher understanding of existence itself.</p>",
				"text": "Plato’s \"Theory of Forms\" argues that the physical world is a mere shadow of a perfect, eternal world of \"Forms.\" The only way to perceive this true reality was through pure reason, and the highest, most rigorous form of this reason was mathematics. For Plato, geometry was the key to unlocking a higher understanding of existence itself.",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b10",
				"kind": "figure",
				"depth": 0,
				"html": "<p><img src=\"/images/the-school-of-athens.jpg\" alt=\"The School of Athens; Raphael (~1510)\"></p>",
				"text": "The School of Athens; Raphael (~1510)",
				"noteIds": [],
				"image": "/images/the-school-of-athens.jpg",
				"caption": "The School of Athens; Raphael (~1510)"
			},
			{
				"id": "b11",
				"kind": "heading",
				"depth": 3,
				"html": "<h3>Aristotle, the Philosopher-Scientist (c. 384–322 BC)</h3>",
				"text": "Aristotle, the Philosopher-Scientist (c. 384–322 BC)",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b12",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>Aristotle was the ultimate philosopher-scientist. His works were not just \"philosophy\" as we know it; they were the foundational texts for:<sup><a href=\"#user-content-fn-2\" id=\"user-content-fnref-2\" data-footnote-ref aria-describedby=\"footnote-label\">1</a></sup></p>",
				"text": "Aristotle was the ultimate philosopher-scientist. His works were not just \"philosophy\" as we know it; they were the foundational texts for:",
				"noteIds": [
					"fn-2"
				],
				"image": null,
				"caption": null
			},
			{
				"id": "b13",
				"kind": "list",
				"depth": 0,
				"html": "<ul>\n<li>Physics (<em>Physics</em>)</li>\n<li>Biology (<em>History of Animals</em>)</li>\n<li>Formal Logic (<em>Prior Analytics</em>)</li>\n<li>Metaphysics (<em>Metaphysics</em>)</li>\n</ul>",
				"text": "Physics (Physics) Biology (History of Animals) Formal Logic (Prior Analytics) Metaphysics (Metaphysics)",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b14",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>For Aristotle, one could not understand ethics or politics without first understanding the <em>nature</em> of the world (physics) and the <em>nature</em> of man (biology, logic). He famously said:</p>",
				"text": "For Aristotle, one could not understand ethics or politics without first understanding the nature of the world (physics) and the nature of man (biology, logic). He famously said:",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b15",
				"kind": "quote",
				"depth": 0,
				"html": "<blockquote>\n<p>\"In all things of nature there is something of the marvelous.\"</p>\n</blockquote>",
				"text": "\"In all things of nature there is something of the marvelous.\"",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b16",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>This holistic approach, where science informed philosophy and vice versa, was the engine of classical progress.</p>",
				"text": "This holistic approach, where science informed philosophy and vice versa, was the engine of classical progress.",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b17",
				"kind": "heading",
				"depth": 2,
				"html": "<h2>II. The First Schism: Theological Subordination</h2>",
				"text": "II. The First Schism: Theological Subordination",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b18",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p><em>c. 529 AD – c. 1500 AD</em></p>",
				"text": "c. 529 AD – c. 1500 AD",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b19",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>The classical integration was deliberately fractured. The primary goal of European thought shifted from <strong>understanding the world</strong> to <strong>justifying God’s plan</strong>. This period began symbolically with the closing of Plato's Academy in 529 AD by Emperor Justinian I, an act that formally subjugated classical inquiry to Christian doctrine.<sup><a href=\"#user-content-fn-3\" id=\"user-content-fnref-3\" data-footnote-ref aria-describedby=\"footnote-label\">1</a></sup></p>",
				"text": "The classical integration was deliberately fractured. The primary goal of European thought shifted from understanding the world to justifying God’s plan. This period began symbolically with the closing of Plato's Academy in 529 AD by Emperor Justinian I, an act that formally subjugated classical inquiry to Christian doctrine.",
				"noteIds": [
					"fn-3"
				],
				"image": null,
				"caption": null
			},
			{
				"id": "b20",
				"kind": "heading",
				"depth": 3,
				"html": "<h3>The Rise of Theocentrism</h3>",
				"text": "The Rise of Theocentrism",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b21",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>With the fall of the Western Roman Empire, the Church became the singular, unifying political and intellectual power in Europe. This power was maintained by replacing the classical focus on <em>logos</em> (rational inquiry) with a focus on <em>theos</em> (God).</p>",
				"text": "With the fall of the Western Roman Empire, the Church became the singular, unifying political and intellectual power in Europe. This power was maintained by replacing the classical focus on logos (rational inquiry) with a focus on theos (God).",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b22",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>Truth was no longer discovered; it was <strong>revealed</strong> through scripture and interpreted by the Church hierarchy. Philosophy's new role, as articulated by thinkers like Thomas Aquinas, was to be the \"handmaiden of theology.\" Its purpose was solely to explain and defend religious doctrine.<sup><a href=\"#user-content-fn-4\" id=\"user-content-fnref-4\" data-footnote-ref aria-describedby=\"footnote-label\">1</a></sup></p>",
				"text": "Truth was no longer discovered; it was revealed through scripture and interpreted by the Church hierarchy. Philosophy's new role, as articulated by thinkers like Thomas Aquinas, was to be the \"handmaiden of theology.\" Its purpose was solely to explain and defend religious doctrine.",
				"noteIds": [
					"fn-4"
				],
				"image": null,
				"caption": null
			},
			{
				"id": "b23",
				"kind": "heading",
				"depth": 3,
				"html": "<h3>The Suppression of Scientific Inquiry</h3>",
				"text": "The Suppression of Scientific Inquiry",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b24",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>The schism did not just halt progress; it actively suppressed it. Science was forced underground, often associated with heresy.</p>",
				"text": "The schism did not just halt progress; it actively suppressed it. Science was forced underground, often associated with heresy.",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b25",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>Leonardo da Vinci (1452-1519) had to conduct his revolutionary anatomical studies by dissecting human corpses in secret, directly defying Church law, to advance modern medicine. His work was, by necessity, hidden.<sup><a href=\"#user-content-fn-5\" id=\"user-content-fnref-5\" data-footnote-ref aria-describedby=\"footnote-label\">1</a></sup></p>",
				"text": "Leonardo da Vinci (1452-1519) had to conduct his revolutionary anatomical studies by dissecting human corpses in secret, directly defying Church law, to advance modern medicine. His work was, by necessity, hidden.",
				"noteIds": [
					"fn-5"
				],
				"image": null,
				"caption": null
			},
			{
				"id": "b26",
				"kind": "quote",
				"depth": 0,
				"html": "<blockquote>\n<p>\"Nature is the source of all true knowledge. She has her own logic, her own laws, she has no effect without cause nor invention without necessity.\" - Leonardo da Vinci</p>\n</blockquote>",
				"text": "\"Nature is the source of all true knowledge. She has her own logic, her own laws, she has no effect without cause nor invention without necessity.\" - Leonardo da Vinci",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b27",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>Decades later, it is widely theorized that Michelangelo (1475-1564) embedded a subversively scientific message in his most famous work. In \"The Creation of Adam\" on the Sistine Chapel ceiling, the shroud surrounding God forms a perfect, anatomically correct diagram of the human brain. This is interpreted as a hidden assertion that divine power is a product of <strong>human intellect</strong>—a dangerous, heretical idea that placed reason on par with God, hidden in plain sight from the Pope.<sup><a href=\"#user-content-fn-6\" id=\"user-content-fnref-6\" data-footnote-ref aria-describedby=\"footnote-label\">1</a></sup></p>",
				"text": "Decades later, it is widely theorized that Michelangelo (1475-1564) embedded a subversively scientific message in his most famous work. In \"The Creation of Adam\" on the Sistine Chapel ceiling, the shroud surrounding God forms a perfect, anatomically correct diagram of the human brain. This is interpreted as a hidden assertion that divine power is a product of human intellect—a dangerous, heretical idea that placed reason on par with God, hidden in plain sight from the Pope.",
				"noteIds": [
					"fn-6"
				],
				"image": null,
				"caption": null
			},
			{
				"id": "b28",
				"kind": "figure",
				"depth": 0,
				"html": "<p><img src=\"/images/the-creation-of-adam.webp\" alt=\"The Creation of Adam; Michelangelo (~1510), (Composite View, credit F. L. Meshberger)\"></p>",
				"text": "The Creation of Adam; Michelangelo (~1510), (Composite View, credit F. L. Meshberger)",
				"noteIds": [],
				"image": "/images/the-creation-of-adam.webp",
				"caption": "The Creation of Adam; Michelangelo (~1510), (Composite View, credit F. L. Meshberger)"
			},
			{
				"id": "b29",
				"kind": "heading",
				"depth": 3,
				"html": "<h3>The Punishment of Truth: Galileo's Trial</h3>",
				"text": "The Punishment of Truth: Galileo's Trial",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b30",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>When this hidden science finally became too bold to ignore, suppression turned to punishment. The Trial of Galileo in 1633 is the definitive example.<sup><a href=\"#user-content-fn-7\" id=\"user-content-fnref-7\" data-footnote-ref aria-describedby=\"footnote-label\">1</a></sup></p>",
				"text": "When this hidden science finally became too bold to ignore, suppression turned to punishment. The Trial of Galileo in 1633 is the definitive example.",
				"noteIds": [
					"fn-7"
				],
				"image": null,
				"caption": null
			},
			{
				"id": "b31",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>Galileo used a telescope to gather empirical data, such as the phases of Venus and the moons of Jupiter, which proved the Heliocentric (sun-centered) model. The Church establishment, whose political and philosophical authority was tied to the Geocentric (Earth-centered) model, declared this a heresy. Galileo was forced to recant.</p>",
				"text": "Galileo used a telescope to gather empirical data, such as the phases of Venus and the moons of Jupiter, which proved the Heliocentric (sun-centered) model. The Church establishment, whose political and philosophical authority was tied to the Geocentric (Earth-centered) model, declared this a heresy. Galileo was forced to recant.",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b32",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>Theologians, in their role as thinkers, used their power to suppress the fundamental scientist. This act demonstrates the schism perfectly: critical thought based on evidence was subordinated to power based on dogma.</p>",
				"text": "Theologians, in their role as thinkers, used their power to suppress the fundamental scientist. This act demonstrates the schism perfectly: critical thought based on evidence was subordinated to power based on dogma.",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b33",
				"kind": "figure",
				"depth": 0,
				"html": "<p><img src=\"/images/galileo-facing-the-roman-inquisition.jpg\" alt=\"Galileo facing the Roman Inquisition; Cristiano Banti (1857)\"></p>",
				"text": "Galileo facing the Roman Inquisition; Cristiano Banti (1857)",
				"noteIds": [],
				"image": "/images/galileo-facing-the-roman-inquisition.jpg",
				"caption": "Galileo facing the Roman Inquisition; Cristiano Banti (1857)"
			},
			{
				"id": "b34",
				"kind": "heading",
				"depth": 2,
				"html": "<h2>III. The Reunion: The Enlightenment</h2>",
				"text": "III. The Reunion: The Enlightenment",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b35",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p><em>c. 1687 – c. 1800</em></p>",
				"text": "c. 1687 – c. 1800",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b36",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>The first schism was dismantled by a powerful reintegration, with fundamental science providing the very tools philosophers needed to break free from dogma.</p>",
				"text": "The first schism was dismantled by a powerful reintegration, with fundamental science providing the very tools philosophers needed to break free from dogma.",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b37",
				"kind": "heading",
				"depth": 3,
				"html": "<h3>Newton's \"Clockwork Universe\"</h3>",
				"text": "Newton's \"Clockwork Universe\"",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b38",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>The catalyst for this reunion was Isaac Newton’s <em>Philosophiæ Naturalis Principia Mathematica</em> (1687). In this work, Newton proved that the entire cosmos, from a falling apple to the orbits of planets, was governed by <strong>discoverable, rational, mathematical laws</strong>.<sup><a href=\"#user-content-fn-8\" id=\"user-content-fnref-8\" data-footnote-ref aria-describedby=\"footnote-label\">1</a></sup> This effectively \"killed\" the medieval God of daily miracles and replaced him with a \"Clockmaker God\" who created the system and let it run. This opened the door for human reason to become the primary authority.</p>",
				"text": "The catalyst for this reunion was Isaac Newton’s Philosophiæ Naturalis Principia Mathematica (1687). In this work, Newton proved that the entire cosmos, from a falling apple to the orbits of planets, was governed by discoverable, rational, mathematical laws. This effectively \"killed\" the medieval God of daily miracles and replaced him with a \"Clockmaker God\" who created the system and let it run. This opened the door for human reason to become the primary authority.",
				"noteIds": [
					"fn-8"
				],
				"image": null,
				"caption": null
			},
			{
				"id": "b39",
				"kind": "quote",
				"depth": 0,
				"html": "<blockquote>\n<p>\"I frame no hypotheses; for whatever is not deduced from the phenomena is to be called an hypothesis; and hypotheses, whether metaphysical or physical, whether of occult qualities or mechanical, have no place in experimental philosophy.\" - Isaac Newton</p>\n</blockquote>",
				"text": "\"I frame no hypotheses; for whatever is not deduced from the phenomena is to be called an hypothesis; and hypotheses, whether metaphysical or physical, whether of occult qualities or mechanical, have no place in experimental philosophy.\" - Isaac Newton",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b40",
				"kind": "figure",
				"depth": 0,
				"html": "<p><img src=\"/images/principia-mathematica.png\" alt=\"Philosophiæ Naturalis Principia Mathematica; Isaac Newton (1687)\"></p>",
				"text": "Philosophiæ Naturalis Principia Mathematica; Isaac Newton (1687)",
				"noteIds": [],
				"image": "/images/principia-mathematica.png",
				"caption": "Philosophiæ Naturalis Principia Mathematica; Isaac Newton (1687)"
			},
			{
				"id": "b41",
				"kind": "heading",
				"depth": 3,
				"html": "<h3>The Enthronement of Reason</h3>",
				"text": "The Enthronement of Reason",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b42",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>Enlightenment Philosophers used Newton's scientific certainty as a weapon against the \"superstition\" and \"irrationality\" of the Church and monarchy. In France, Diderot’s <em>Encyclopédie</em> (1751–1772) was the practical application: an attempt to catalog all human knowledge based on <strong>reason and science</strong>.<sup><a href=\"#user-content-fn-9\" id=\"user-content-fnref-9\" data-footnote-ref aria-describedby=\"footnote-label\">1</a></sup> This movement led directly to the <strong>French Revolution</strong> and the concept of <em>laïcité</em> (secularism).</p>",
				"text": "Enlightenment Philosophers used Newton's scientific certainty as a weapon against the \"superstition\" and \"irrationality\" of the Church and monarchy. In France, Diderot’s Encyclopédie (1751–1772) was the practical application: an attempt to catalog all human knowledge based on reason and science. This movement led directly to the French Revolution and the concept of laïcité (secularism).",
				"noteIds": [
					"fn-9"
				],
				"image": null,
				"caption": null
			},
			{
				"id": "b43",
				"kind": "figure",
				"depth": 0,
				"html": "<p><img src=\"/images/encyclopedie.jpg\" alt=\"L’Encyclopédie ou Dictionnaire raisonné des sciences, des arts et des métiers; Denis Diderot (1751–1772)\"></p>",
				"text": "L’Encyclopédie ou Dictionnaire raisonné des sciences, des arts et des métiers; Denis Diderot (1751–1772)",
				"noteIds": [],
				"image": "/images/encyclopedie.jpg",
				"caption": "L’Encyclopédie ou Dictionnaire raisonné des sciences, des arts et des métiers; Denis Diderot (1751–1772)"
			},
			{
				"id": "b44",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>This was not an isolated French phenomenon. In the <strong>Scottish Enlightenment</strong>, thinkers like Adam Smith (<em>The Wealth of Nations</em>) attempted to create a \"science\" of economics based on natural laws.<sup><a href=\"#user-content-fn-10\" id=\"user-content-fnref-10\" data-footnote-ref aria-describedby=\"footnote-label\">1</a></sup> In <strong>Prussia</strong>, Immanuel Kant defined the movement with the motto <em>Sapere aude</em> (\"Dare to know\"), casting the use of one's own reason as a moral imperative.<sup><a href=\"#user-content-fn-11\" id=\"user-content-fnref-11\" data-footnote-ref aria-describedby=\"footnote-label\">2</a></sup></p>",
				"text": "This was not an isolated French phenomenon. In the Scottish Enlightenment, thinkers like Adam Smith (The Wealth of Nations) attempted to create a \"science\" of economics based on natural laws. In Prussia, Immanuel Kant defined the movement with the motto Sapere aude (\"Dare to know\"), casting the use of one's own reason as a moral imperative.",
				"noteIds": [
					"fn-10",
					"fn-11"
				],
				"image": null,
				"caption": null
			},
			{
				"id": "b45",
				"kind": "quote",
				"depth": 0,
				"html": "<blockquote>\n<p>\"The death of dogma is the birth of morality.\" – Immanuel Kant</p>\n</blockquote>",
				"text": "\"The death of dogma is the birth of morality.\" – Immanuel Kant",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b46",
				"kind": "heading",
				"depth": 2,
				"html": "<h2>IV. The Second Schism: Ideological Subordination</h2>",
				"text": "IV. The Second Schism: Ideological Subordination",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b47",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p><em>c. 1900 – Present</em></p>",
				"text": "c. 1900 – Present",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b48",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>The 20th and 21st centuries are defined by a new schism. The complexity of fields like quantum physics and molecular biology has been used to justify a detachment of social and political philosophy from fundamental science.</p>",
				"text": "The 20th and 21st centuries are defined by a new schism. The complexity of fields like quantum physics and molecular biology has been used to justify a detachment of social and political philosophy from fundamental science.",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b49",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>This schism subordinates empirical reality not to theology, but to <strong>political and social ideologies</strong>, leading to nonsensical positions, performative governance, and a loss of strategic autonomy.</p>",
				"text": "This schism subordinates empirical reality not to theology, but to political and social ideologies, leading to nonsensical positions, performative governance, and a loss of strategic autonomy.",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b50",
				"kind": "heading",
				"depth": 3,
				"html": "<h3>Case Study 1: Agriculture and GMOs</h3>",
				"text": "Case Study 1: Agriculture and GMOs",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b51",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>The first example is found in agriculture, specifically the EU's policy on GMOs. The ideological position is a widespread European ideology, formalized in the \"precautionary principle,\" that views \"naturalness\" as an intrinsic good. This philosophy, promoted by powerful political and NGO groups, casts genetic modification (GMO) as an \"unnatural\" and hubristic act, regardless of scientific data.<sup><a href=\"#user-content-fn-12\" id=\"user-content-fnref-12\" data-footnote-ref aria-describedby=\"footnote-label\">1</a></sup></p>",
				"text": "The first example is found in agriculture, specifically the EU's policy on GMOs. The ideological position is a widespread European ideology, formalized in the \"precautionary principle,\" that views \"naturalness\" as an intrinsic good. This philosophy, promoted by powerful political and NGO groups, casts genetic modification (GMO) as an \"unnatural\" and hubristic act, regardless of scientific data.",
				"noteIds": [
					"fn-12"
				],
				"image": null,
				"caption": null
			},
			{
				"id": "b52",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>On the other hand, the fundamental science of biology and environmental science shows that genetic modification (e.g., CRISPR) is a precise tool for achieving a result, like pest resistance, that humans have been doing clumsily for millennia via \"natural\" cross-breeding. Genetically modified crops are a proven tool for achieving stated European goals. They can be engineered to drastically reduce the need for pesticides, resist drought, and increase yields.</p>",
				"text": "On the other hand, the fundamental science of biology and environmental science shows that genetic modification (e.g., CRISPR) is a precise tool for achieving a result, like pest resistance, that humans have been doing clumsily for millennia via \"natural\" cross-breeding. Genetically modified crops are a proven tool for achieving stated European goals. They can be engineered to drastically reduce the need for pesticides, resist drought, and increase yields.",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b53",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>The irrational outcome of this ideological stance is the EU’s de facto ban on the cultivation of most GM crops. This political decision has stifled innovation, caused brain drain, and prevented pesticide reductions. It is a clear case of a social philosophy (\"naturalness\") winning out over the fundamental science of biology, to the detriment of the environment and economy.<sup><a href=\"#user-content-fn-13\" id=\"user-content-fnref-13\" data-footnote-ref aria-describedby=\"footnote-label\">1</a></sup></p>",
				"text": "The irrational outcome of this ideological stance is the EU’s de facto ban on the cultivation of most GM crops. This political decision has stifled innovation, caused brain drain, and prevented pesticide reductions. It is a clear case of a social philosophy (\"naturalness\") winning out over the fundamental science of biology, to the detriment of the environment and economy.",
				"noteIds": [
					"fn-13"
				],
				"image": null,
				"caption": null
			},
			{
				"id": "b54",
				"kind": "heading",
				"depth": 3,
				"html": "<h3>Case Study 2: Education and the Reading Wars</h3>",
				"text": "Case Study 2: Education and the Reading Wars",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b55",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>A second example can be seen in education, with the \"whole language\" debate. The ideological position was a dominant 20th-century educational philosophy, especially strong in France (<em>la méthode globale</em>) and the UK. It argued that learning to read is a \"natural\" process, like learning to speak. It claimed that explicit <strong>phonics</strong> (sounding out letters) was \"authoritarian\" and would kill a child's \"love of reading.\" This was a social-political theory about child liberation.</p>",
				"text": "A second example can be seen in education, with the \"whole language\" debate. The ideological position was a dominant 20th-century educational philosophy, especially strong in France (la méthode globale) and the UK. It argued that learning to read is a \"natural\" process, like learning to speak. It claimed that explicit phonics (sounding out letters) was \"authoritarian\" and would kill a child's \"love of reading.\" This was a social-political theory about child liberation.",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b56",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>However, the fundamental science of cognitive neuroscience and fMRI scanning shows that the human brain is <strong>not</strong> wired to read. Speaking is innate; reading is a learned skill that requires retraining parts of the brain. Brain imaging proves that reading requires the brain to build a new pathway to decode letters into sounds. \"Whole language\" (guessing from pictures) activates the wrong part of the brain. <strong>Explicit phonics</strong> is the only method that reliably builds the correct neural architecture.<sup><a href=\"#user-content-fn-14\" id=\"user-content-fnref-14\" data-footnote-ref aria-describedby=\"footnote-label\">1</a></sup></p>",
				"text": "However, the fundamental science of cognitive neuroscience and fMRI scanning shows that the human brain is not wired to read. Speaking is innate; reading is a learned skill that requires retraining parts of the brain. Brain imaging proves that reading requires the brain to build a new pathway to decode letters into sounds. \"Whole language\" (guessing from pictures) activates the wrong part of the brain. Explicit phonics is the only method that reliably builds the correct neural architecture.",
				"noteIds": [
					"fn-14"
				],
				"image": null,
				"caption": null
			},
			{
				"id": "b57",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>The irrational outcome was that generations of children were passed through school without being given the fundamental tools to read, contributing to a literacy crisis where <strong>one in five Europeans is functionally illiterate</strong>.<sup><a href=\"#user-content-fn-15\" id=\"user-content-fnref-15\" data-footnote-ref aria-describedby=\"footnote-label\">1</a></sup> This was a direct result of educational \"thinkers\" allowing their social ideology to overrule the hard evidence from neuroscience.</p>",
				"text": "The irrational outcome was that generations of children were passed through school without being given the fundamental tools to read, contributing to a literacy crisis where one in five Europeans is functionally illiterate. This was a direct result of educational \"thinkers\" allowing their social ideology to overrule the hard evidence from neuroscience.",
				"noteIds": [
					"fn-15"
				],
				"image": null,
				"caption": null
			},
			{
				"id": "b58",
				"kind": "figure",
				"depth": 0,
				"html": "<p><img src=\"/images/fmri.png\" alt=\"fMRI scans for different tasks - Feasibility, Contrast Sensitivity and Network Specificity of Language fMRI in Presurgical Evaluation for Epilepsy and Brain Tumor Surgery\"></p>",
				"text": "fMRI scans for different tasks - Feasibility, Contrast Sensitivity and Network Specificity of Language fMRI in Presurgical Evaluation for Epilepsy and Brain Tumor Surgery",
				"noteIds": [],
				"image": "/images/fmri.png",
				"caption": "fMRI scans for different tasks - Feasibility, Contrast Sensitivity and Network Specificity of Language fMRI in Presurgical Evaluation for Epilepsy and Brain Tumor Surgery"
			},
			{
				"id": "b59",
				"kind": "heading",
				"depth": 3,
				"html": "<h3>Case Study 3: Energy and the <em>Energiewende</em></h3>",
				"text": "Case Study 3: Energy and the Energiewende",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b60",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>The third example is Germany's energy policy, the <em>Energiewende</em>. The ideological position, core to the German Green Party, holds that nuclear power is categorically evil and an unacceptable risk. This position of social values predates the climate change debate.</p>",
				"text": "The third example is Germany's energy policy, the Energiewende. The ideological position, core to the German Green Party, holds that nuclear power is categorically evil and an unacceptable risk. This position of social values predates the climate change debate.",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b61",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>This ideology clashes with the fundamental science of physics and engineering. Physics shows that the primary driver of climate change is <strong>CO2</strong>, and the most efficient, reliable, and high-density way to produce zero-carbon electricity is <strong>nuclear fission</strong>. Furthermore, engineering and grid science show that a modern grid requires a stable, 24/7 \"baseload\" power source. Wind and solar are intermittent and, without mass-scale battery technology, cannot provide this baseload.</p>",
				"text": "This ideology clashes with the fundamental science of physics and engineering. Physics shows that the primary driver of climate change is CO2, and the most efficient, reliable, and high-density way to produce zero-carbon electricity is nuclear fission. Furthermore, engineering and grid science show that a modern grid requires a stable, 24/7 \"baseload\" power source. Wind and solar are intermittent and, without mass-scale battery technology, cannot provide this baseload.",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b62",
				"kind": "table",
				"depth": 0,
				"html": "<table>\n<thead>\n<tr>\n<th align=\"left\"></th>\n<th align=\"left\">Fuel Energy Density (GJ/kg)</th>\n<th align=\"left\">Lifetime CO₂ Emissions (g CO₂eq/kWh)</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td align=\"left\"><strong>Nuclear</strong></td>\n<td align=\"left\">~3,500</td>\n<td align=\"left\">~12</td>\n</tr>\n<tr>\n<td align=\"left\"><strong>Natural Gas</strong></td>\n<td align=\"left\">~0.05</td>\n<td align=\"left\">~490</td>\n</tr>\n<tr>\n<td align=\"left\"><strong>Oil</strong></td>\n<td align=\"left\">~0.042</td>\n<td align=\"left\">~733</td>\n</tr>\n<tr>\n<td align=\"left\"><strong>Coal</strong></td>\n<td align=\"left\">~0.03</td>\n<td align=\"left\">~820</td>\n</tr>\n<tr>\n<td align=\"left\"><strong>Hydropower</strong></td>\n<td align=\"left\">N/A (Flow)</td>\n<td align=\"left\">~24</td>\n</tr>\n</tbody>\n</table>",
				"text": "Fuel Energy Density (GJ/kg) Lifetime CO₂ Emissions (g CO₂eq/kWh) Nuclear ~3,500 ~12 Natural Gas ~0.05 ~490 Oil ~0.042 ~733 Coal ~0.03 ~820 Hydropower N/A (Flow) ~24",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b63",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>The irrational outcome of this ideology was the decision to shut down Germany’s zero-carbon nuclear plants before a renewable replacement was scientifically viable. This forced a return to the only available baseload alternative: <strong>lignite coal</strong>, the single most CO2-polluting fossil fuel. The thinkers, in pursuit of their social goal, directly contradicted their stated goal of saving the climate by ignoring the fundamental science of physics.<sup><a href=\"#user-content-fn-16\" id=\"user-content-fnref-16\" data-footnote-ref aria-describedby=\"footnote-label\">1</a></sup></p>",
				"text": "The irrational outcome of this ideology was the decision to shut down Germany’s zero-carbon nuclear plants before a renewable replacement was scientifically viable. This forced a return to the only available baseload alternative: lignite coal, the single most CO2-polluting fossil fuel. The thinkers, in pursuit of their social goal, directly contradicted their stated goal of saving the climate by ignoring the fundamental science of physics.",
				"noteIds": [
					"fn-16"
				],
				"image": null,
				"caption": null
			},
			{
				"id": "b64",
				"kind": "heading",
				"depth": 2,
				"html": "<h2>V. A New Synthesis : Hyper Anabasis</h2>",
				"text": "V. A New Synthesis : Hyper Anabasis",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b65",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>The evidence suggests a recurring pattern in European intellectual history: a flourishing of progress during periods of synthesis between the philosophical and the scientific, and a subsequent decline when they diverge. The parallels between the First Schism of the medieval era and the Second Schism of the modern age are worthy of serious consideration.</p>",
				"text": "The evidence suggests a recurring pattern in European intellectual history: a flourishing of progress during periods of synthesis between the philosophical and the scientific, and a subsequent decline when they diverge. The parallels between the First Schism of the medieval era and the Second Schism of the modern age are worthy of serious consideration.",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b66",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>This historical framework compels us to ask a critical question: are our current crises, be they environmental, political, or educational, the inevitable result of a philosophy detached from empiricism?</p>",
				"text": "This historical framework compels us to ask a critical question: are our current crises, be they environmental, political, or educational, the inevitable result of a philosophy detached from empiricism?",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b67",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>If so, the path forward is not to repeat the past, but to begin a philosophical successor to the Enlightenment. I call this movement <strong>Hyper Anabasis</strong><sup><a href=\"#user-content-fn-17\" id=\"user-content-fnref-17\" data-footnote-ref aria-describedby=\"footnote-label\">1</a></sup>: a \"great ascent\" beyond our present limitations, dedicated to permanently reuniting our governing philosophies with the sciences.</p>",
				"text": "If so, the path forward is not to repeat the past, but to begin a philosophical successor to the Enlightenment. I call this movement Hyper Anabasis: a \"great ascent\" beyond our present limitations, dedicated to permanently reuniting our governing philosophies with the sciences.",
				"noteIds": [
					"fn-17"
				],
				"image": null,
				"caption": null
			},
			{
				"id": "b68",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p>The most practical step towards this new era is a profound and sustained investment in scientific literacy at every level of society. From primary school curricula to the continuing education of public servants, we must cultivate a culture of critical thinking and empirical curiosity. Only a population that values evidence can produce policy that does the same.</p>",
				"text": "The most practical step towards this new era is a profound and sustained investment in scientific literacy at every level of society. From primary school curricula to the continuing education of public servants, we must cultivate a culture of critical thinking and empirical curiosity. Only a population that values evidence can produce policy that does the same.",
				"noteIds": [],
				"image": null,
				"caption": null
			},
			{
				"id": "b69",
				"kind": "paragraph",
				"depth": 0,
				"html": "<p><strong>We must place fundamental science back to its rightful position: the foundation upon which our philosophies, policies, and societies are built.</strong></p>",
				"text": "We must place fundamental science back to its rightful position: the foundation upon which our philosophies, policies, and societies are built.",
				"noteIds": [],
				"image": null,
				"caption": null
			}
		]
	}
]

export const roles = [
	{
		"id": "lorem-ipsum-2022-03",
		"title": "Senior Software Engineer",
		"company": "Lorem Ipsum",
		"location": "Earth",
		"start": "2022-03",
		"end": null,
		"summary": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		"highlights": [
			"Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
			"Duis aute irure dolor in reprehenderit in voluptate velit esse cillum.",
			"Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia."
		],
		"stack": [
			"TypeScript",
			"Vue",
			"Cloudflare Workers"
		]
	},
	{
		"id": "dolor-sit-2020-01",
		"title": "Full Stack Engineer",
		"company": "Dolor Sit",
		"location": "Earth",
		"start": "2020-01",
		"end": "2022-02",
		"summary": "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.",
		"highlights": [
			"Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit.",
			"Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet."
		],
		"stack": [
			"Node.js",
			"GraphQL",
			"PostgreSQL"
		]
	},
	{
		"id": "amet-consectetur-2018-06",
		"title": "Frontend Engineer",
		"company": "Amet Consectetur",
		"location": "Earth",
		"start": "2018-06",
		"end": "2019-12",
		"summary": "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque.",
		"highlights": [
			"Et harum quidem rerum facilis est et expedita distinctio.",
			"Temporibus autem quibusdam et aut officiis debitis aut rerum."
		],
		"stack": [
			"JavaScript",
			"React",
			"Webpack"
		]
	},
	{
		"id": "adipiscing-elit-2016-09",
		"title": "Software Engineer",
		"company": "Adipiscing Elit",
		"location": "Earth",
		"start": "2016-09",
		"end": "2018-05",
		"summary": "Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat.",
		"highlights": [
			"Omnis voluptas assumenda est, omnis dolor repellendus.",
			"Itaque earum rerum hic tenetur a sapiente delectus."
		],
		"stack": [
			"PHP",
			"MySQL",
			"jQuery"
		]
	}
]

export const schools = [
	{
		"id": "supinfo-2011-09",
		"qualification": "Master of Engineering, Computer Science",
		"school": "Supinfo",
		"location": "Earth",
		"start": "2011-09",
		"end": "2016-06",
		"summary": "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur."
	}
]

export const content = { site, shelves, posts, roles, schools }

export default content
