/** This file is automatically generated by Flamme. Do not edit. */
// source: src/pages/blog/+page.gql
import type { Artifact } from '@flamme/runtime'

const artifact = {
    "name": "Blog",
    "kind": "query",
    "hash": "005f81b8ed135e4aa88b604418df33209d54b489acfac8689db67af35a40c517",
    "raw": `query Blog {
    posts {
        __typename
        date
        description
        slug
        tags
        title
    }
    site {
        __typename
        date
        name
    }
}
`,

    "rootType": "Query",
    "stripVariables": [] as Array<string>,

    "selection": {
        "fields": {
            "posts": {
                "type": "Post",
                "modifiers": "[Post!]",
                "keyRaw": "posts",
                "nullable": true,

                "selection": {
                    "fields": {
                        "__typename": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "__typename",
                        },

                        "date": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "date",
                            "visible": true,
                        },

                        "description": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "description",
                            "visible": true,
                        },

                        "slug": {
                            "type": "ID",
                            "modifiers": "ID!",
                            "keyRaw": "slug",
                            "visible": true,
                        },

                        "tags": {
                            "type": "String",
                            "modifiers": "[String!]!",
                            "keyRaw": "tags",
                            "visible": true,
                        },

                        "title": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "title",
                            "visible": true,
                        },
                    },
                },
                "visible": true,
            },

            "site": {
                "type": "Site",
                "modifiers": "Site",
                "keyRaw": "site",
                "nullable": true,

                "selection": {
                    "fields": {
                        "__typename": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "__typename",
                        },

                        "date": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "date",
                            "visible": true,
                        },

                        "name": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "name",
                            "visible": true,
                        },
                    },
                },
                "visible": true,
            },
        },
    },

    "input": {
        "fields": {},

        "types": {},

        "defaults": {},

        "runtimeScalars": {},
    },

    "pluginData": {},
    "policy": "CacheOrNetwork",
    "partial": false
} as const

export type Blog$artifact = typeof artifact

/** Runtime handle for `Blog`. This is what a `.gql` import or the generated barrel yields. */
export type Blog = Artifact<'query', Blog$result, Blog$input, never>

export type Blog$result = {
	readonly site: {
		readonly name: string;
		readonly date: string;
		readonly " $loadingFrame"?: undefined;
	} | null;
	readonly posts: ReadonlyArray<{
		readonly slug: string;
		readonly title: string;
		readonly description: string;
		readonly date: string;
		readonly tags: ReadonlyArray<string>;
		readonly " $loadingFrame"?: undefined;
	}> | null;
};

export type Blog$input = Record<string, never>;

export type Blog$unmasked = {
	readonly site: {
		readonly __typename: "Site";
		readonly name: string;
		readonly date: string;
	} | null;
	readonly posts: ReadonlyArray<{
		readonly __typename: "Post";
		readonly slug: string;
		readonly title: string;
		readonly description: string;
		readonly date: string;
		readonly tags: ReadonlyArray<string>;
	}> | null;
};

const document: Blog = artifact as unknown as Blog

export default document
