/** This file is automatically generated by Flamme. Do not edit. */
// source: src/pages/+layout.gql
import type { Artifact } from '@flamme/runtime'

const artifact = {
    "name": "Chrome",
    "kind": "query",
    "hash": "8a1ec133d9c631658a677b499523eae0d4a620acfe277bb8c8aeafd2b3b05cf2",
    "raw": `query Chrome {
    site {
        __typename
        date
        name
        tagline
    }
}
`,

    "rootType": "Query",
    "stripVariables": [] as Array<string>,

    "selection": {
        "fields": {
            "site": {
                "type": "Site",
                "modifiers": "Site",
                "keyRaw": "site",
                "nullable": true,

                "selection": {
                    "fields": {
                        "__typename": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "__typename",
                        },

                        "date": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "date",
                            "visible": true,
                        },

                        "name": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "name",
                            "visible": true,
                        },

                        "tagline": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "tagline",
                            "visible": true,
                        },
                    },
                },
                "visible": true,
            },
        },
    },

    "input": {
        "fields": {},

        "types": {},

        "defaults": {},

        "runtimeScalars": {},
    },

    "pluginData": {},
    "policy": "CacheOrNetwork",
    "partial": false
} as const

export type Chrome$artifact = typeof artifact

/** Runtime handle for `Chrome`. This is what a `.gql` import or the generated barrel yields. */
export type Chrome = Artifact<'query', Chrome$result, Chrome$input, never>

export type Chrome$result = {
	readonly site: {
		readonly name: string;
		readonly tagline: string;
		readonly date: string;
		readonly " $loadingFrame"?: undefined;
	} | null;
};

export type Chrome$input = Record<string, never>;

export type Chrome$unmasked = {
	readonly site: {
		readonly __typename: "Site";
		readonly name: string;
		readonly tagline: string;
		readonly date: string;
	} | null;
};

const document: Chrome = artifact as unknown as Chrome

export default document
