/** This file is automatically generated by Flamme. Do not edit. */
// source: src/pages/experience/+page.gql
import type { Artifact } from '@flamme/runtime'

const artifact = {
    "name": "Experience",
    "kind": "query",
    "hash": "53c16505d633c0f76aa040d8a2be1c5954c89a1dcbdb8588eb15737bdfa6a7de",
    "raw": `query Experience {
    roles {
        __typename
        company
        end
        highlights
        id
        location
        stack
        start
        summary
        title
    }
    schools {
        __typename
        end
        id
        location
        qualification
        school
        start
        summary
    }
}
`,

    "rootType": "Query",
    "stripVariables": [] as Array<string>,

    "selection": {
        "fields": {
            "roles": {
                "type": "Role",
                "modifiers": "[Role!]",
                "keyRaw": "roles",
                "nullable": true,

                "selection": {
                    "fields": {
                        "__typename": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "__typename",
                        },

                        "company": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "company",
                            "visible": true,
                        },

                        "end": {
                            "type": "String",
                            "modifiers": "String",
                            "keyRaw": "end",
                            "nullable": true,
                            "visible": true,
                        },

                        "highlights": {
                            "type": "String",
                            "modifiers": "[String!]!",
                            "keyRaw": "highlights",
                            "visible": true,
                        },

                        "id": {
                            "type": "ID",
                            "modifiers": "ID!",
                            "keyRaw": "id",
                            "visible": true,
                        },

                        "location": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "location",
                            "visible": true,
                        },

                        "stack": {
                            "type": "String",
                            "modifiers": "[String!]!",
                            "keyRaw": "stack",
                            "visible": true,
                        },

                        "start": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "start",
                            "visible": true,
                        },

                        "summary": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "summary",
                            "visible": true,
                        },

                        "title": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "title",
                            "visible": true,
                        },
                    },
                },
                "visible": true,
            },

            "schools": {
                "type": "School",
                "modifiers": "[School!]",
                "keyRaw": "schools",
                "nullable": true,

                "selection": {
                    "fields": {
                        "__typename": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "__typename",
                        },

                        "end": {
                            "type": "String",
                            "modifiers": "String",
                            "keyRaw": "end",
                            "nullable": true,
                            "visible": true,
                        },

                        "id": {
                            "type": "ID",
                            "modifiers": "ID!",
                            "keyRaw": "id",
                            "visible": true,
                        },

                        "location": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "location",
                            "visible": true,
                        },

                        "qualification": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "qualification",
                            "visible": true,
                        },

                        "school": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "school",
                            "visible": true,
                        },

                        "start": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "start",
                            "visible": true,
                        },

                        "summary": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "summary",
                            "visible": true,
                        },
                    },
                },
                "visible": true,
            },
        },
    },

    "input": {
        "fields": {},

        "types": {},

        "defaults": {},

        "runtimeScalars": {},
    },

    "pluginData": {},
    "policy": "CacheOrNetwork",
    "partial": false
} as const

export type Experience$artifact = typeof artifact

/** Runtime handle for `Experience`. This is what a `.gql` import or the generated barrel yields. */
export type Experience = Artifact<'query', Experience$result, Experience$input, never>

export type Experience$result = {
	readonly roles: ReadonlyArray<{
		readonly id: string;
		readonly title: string;
		readonly company: string;
		readonly location: string;
		readonly start: string;
		readonly end: string | null;
		readonly summary: string;
		readonly highlights: ReadonlyArray<string>;
		readonly stack: ReadonlyArray<string>;
		readonly " $loadingFrame"?: undefined;
	}> | null;
	readonly schools: ReadonlyArray<{
		readonly id: string;
		readonly qualification: string;
		readonly school: string;
		readonly location: string;
		readonly start: string;
		readonly end: string | null;
		readonly summary: string;
		readonly " $loadingFrame"?: undefined;
	}> | null;
};

export type Experience$input = Record<string, never>;

export type Experience$unmasked = {
	readonly roles: ReadonlyArray<{
		readonly __typename: "Role";
		readonly id: string;
		readonly title: string;
		readonly company: string;
		readonly location: string;
		readonly start: string;
		readonly end: string | null;
		readonly summary: string;
		readonly highlights: ReadonlyArray<string>;
		readonly stack: ReadonlyArray<string>;
	}> | null;
	readonly schools: ReadonlyArray<{
		readonly __typename: "School";
		readonly id: string;
		readonly qualification: string;
		readonly school: string;
		readonly location: string;
		readonly start: string;
		readonly end: string | null;
		readonly summary: string;
	}> | null;
};

const document: Experience = artifact as unknown as Experience

export default document
