/** This file is automatically generated by Flamme. Do not edit. */
// source: src/pages/index/+page.gql
import type { Artifact } from '@flamme/runtime'

const artifact = {
    "name": "Home",
    "kind": "query",
    "hash": "1c10df96864e45ae25ce75b31b3056da5d1f714bb0047f29b1251317383ec6be",
    "raw": `query Home {
    site {
        __typename
        date
        name
        tagline
    }
}
`,

    "rootType": "Query",
    "stripVariables": [] as Array<string>,

    "selection": {
        "fields": {
            "site": {
                "type": "Site",
                "modifiers": "Site",
                "keyRaw": "site",
                "nullable": true,

                "selection": {
                    "fields": {
                        "__typename": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "__typename",
                        },

                        "date": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "date",
                            "visible": true,
                        },

                        "name": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "name",
                            "visible": true,
                        },

                        "tagline": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "tagline",
                            "visible": true,
                        },
                    },
                },
                "visible": true,
            },
        },
    },

    "input": {
        "fields": {},

        "types": {},

        "defaults": {},

        "runtimeScalars": {},
    },

    "pluginData": {},
    "policy": "CacheOrNetwork",
    "partial": false
} as const

export type Home$artifact = typeof artifact

/** Runtime handle for `Home`. This is what a `.gql` import or the generated barrel yields. */
export type Home = Artifact<'query', Home$result, Home$input, never>

export type Home$result = {
	readonly site: {
		readonly name: string;
		readonly tagline: string;
		readonly date: string;
		readonly " $loadingFrame"?: undefined;
	} | null;
};

export type Home$input = Record<string, never>;

export type Home$unmasked = {
	readonly site: {
		readonly __typename: "Site";
		readonly name: string;
		readonly tagline: string;
		readonly date: string;
	} | null;
};

const document: Home = artifact as unknown as Home

export default document
