/** This file is automatically generated by Flamme. Do not edit. */
// source: src/pages/library/+page.gql
import type { Artifact } from '@flamme/runtime'

const artifact = {
    "name": "Library",
    "kind": "query",
    "hash": "73997aa786d13ee8bbf70fe6c47e4bc0a7d4d8edbca05d48ada8eb48c8a9fb03",
    "raw": `query Library {
    shelves {
        __typename
        label
        repositories {
            __typename
            archived
            category
            description
            homepage
            language
            name
            stars
            url
        }
        slug
    }
}
`,

    "rootType": "Query",
    "stripVariables": [] as Array<string>,

    "selection": {
        "fields": {
            "shelves": {
                "type": "Shelf",
                "modifiers": "[Shelf!]",
                "keyRaw": "shelves",
                "nullable": true,

                "selection": {
                    "fields": {
                        "__typename": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "__typename",
                        },

                        "label": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "label",
                            "visible": true,
                        },

                        "repositories": {
                            "type": "Repository",
                            "modifiers": "[Repository!]",
                            "keyRaw": "repositories",
                            "nullable": true,

                            "selection": {
                                "fields": {
                                    "__typename": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "__typename",
                                    },

                                    "archived": {
                                        "type": "Boolean",
                                        "modifiers": "Boolean!",
                                        "keyRaw": "archived",
                                        "visible": true,
                                    },

                                    "category": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "category",
                                        "visible": true,
                                    },

                                    "description": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "description",
                                        "visible": true,
                                    },

                                    "homepage": {
                                        "type": "String",
                                        "modifiers": "String",
                                        "keyRaw": "homepage",
                                        "nullable": true,
                                        "visible": true,
                                    },

                                    "language": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "language",
                                        "visible": true,
                                    },

                                    "name": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "name",
                                        "visible": true,
                                    },

                                    "stars": {
                                        "type": "Int",
                                        "modifiers": "Int",
                                        "keyRaw": "stars",
                                        "nullable": true,
                                        "visible": true,
                                    },

                                    "url": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "url",
                                        "visible": true,
                                    },
                                },
                            },
                            "visible": true,
                        },

                        "slug": {
                            "type": "ID",
                            "modifiers": "ID!",
                            "keyRaw": "slug",
                            "visible": true,
                        },
                    },
                },
                "visible": true,
            },
        },
    },

    "input": {
        "fields": {},

        "types": {},

        "defaults": {},

        "runtimeScalars": {},
    },

    "pluginData": {},
    "policy": "CacheOrNetwork",
    "partial": false
} as const

export type Library$artifact = typeof artifact

/** Runtime handle for `Library`. This is what a `.gql` import or the generated barrel yields. */
export type Library = Artifact<'query', Library$result, Library$input, never>

export type Library$result = {
	readonly shelves: ReadonlyArray<{
		readonly slug: string;
		readonly label: string;
		readonly repositories: ReadonlyArray<{
			readonly name: string;
			readonly description: string;
			readonly language: string;
			readonly url: string;
			readonly homepage: string | null;
			readonly archived: boolean;
			readonly category: string;
			readonly stars: number | null;
		}> | null;
		readonly " $loadingFrame"?: undefined;
	}> | null;
};

export type Library$input = Record<string, never>;

export type Library$unmasked = {
	readonly shelves: ReadonlyArray<{
		readonly __typename: "Shelf";
		readonly slug: string;
		readonly label: string;
		readonly repositories: ReadonlyArray<{
			readonly __typename: "Repository";
			readonly name: string;
			readonly description: string;
			readonly language: string;
			readonly url: string;
			readonly homepage: string | null;
			readonly archived: boolean;
			readonly category: string;
			readonly stars: number | null;
		}> | null;
	}> | null;
};

const document: Library = artifact as unknown as Library

export default document
