/** This file is automatically generated by Flamme. Do not edit. */
// source: src/pages/blog/[slug]/+page.gql
import type { Artifact } from '@flamme/runtime'

const artifact = {
    "name": "Post",
    "kind": "query",
    "hash": "b6905f23f8e2a8a4811e996fd2d356dd852ffa715a785af905e441cb8ad80e9f",
    "raw": `query Post($slug: String!) {
    post(slug: $slug) {
        __typename
        blocks {
            __typename
            caption
            depth
            html
            id
            image
            kind
            noteIds
            text
        }
        date
        description
        notes {
            __typename
            html
            id
            number
            text
        }
        slug
        tags
        title
    }
}
`,

    "rootType": "Query",
    "stripVariables": [] as Array<string>,

    "selection": {
        "fields": {
            "post": {
                "type": "Post",
                "modifiers": "Post",
                "keyRaw": "post(slug: $slug)",
                "nullable": true,

                "selection": {
                    "fields": {
                        "__typename": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "__typename",
                        },

                        "blocks": {
                            "type": "Block",
                            "modifiers": "[Block!]",
                            "keyRaw": "blocks",
                            "nullable": true,

                            "selection": {
                                "fields": {
                                    "__typename": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "__typename",
                                    },

                                    "caption": {
                                        "type": "String",
                                        "modifiers": "String",
                                        "keyRaw": "caption",
                                        "nullable": true,
                                        "visible": true,
                                    },

                                    "depth": {
                                        "type": "Int",
                                        "modifiers": "Int!",
                                        "keyRaw": "depth",
                                        "visible": true,
                                    },

                                    "html": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "html",
                                        "visible": true,
                                    },

                                    "id": {
                                        "type": "ID",
                                        "modifiers": "ID!",
                                        "keyRaw": "id",
                                        "visible": true,
                                    },

                                    "image": {
                                        "type": "String",
                                        "modifiers": "String",
                                        "keyRaw": "image",
                                        "nullable": true,
                                        "visible": true,
                                    },

                                    "kind": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "kind",
                                        "visible": true,
                                    },

                                    "noteIds": {
                                        "type": "String",
                                        "modifiers": "[String!]!",
                                        "keyRaw": "noteIds",
                                        "visible": true,
                                    },

                                    "text": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "text",
                                        "visible": true,
                                    },
                                },
                            },
                            "visible": true,
                        },

                        "date": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "date",
                            "visible": true,
                        },

                        "description": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "description",
                            "visible": true,
                        },

                        "notes": {
                            "type": "Note",
                            "modifiers": "[Note!]",
                            "keyRaw": "notes",
                            "nullable": true,

                            "selection": {
                                "fields": {
                                    "__typename": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "__typename",
                                    },

                                    "html": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "html",
                                        "visible": true,
                                    },

                                    "id": {
                                        "type": "ID",
                                        "modifiers": "ID!",
                                        "keyRaw": "id",
                                        "visible": true,
                                    },

                                    "number": {
                                        "type": "Int",
                                        "modifiers": "Int!",
                                        "keyRaw": "number",
                                        "visible": true,
                                    },

                                    "text": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "text",
                                        "visible": true,
                                    },
                                },
                            },
                            "visible": true,
                        },

                        "slug": {
                            "type": "ID",
                            "modifiers": "ID!",
                            "keyRaw": "slug",
                            "visible": true,
                        },

                        "tags": {
                            "type": "String",
                            "modifiers": "[String!]!",
                            "keyRaw": "tags",
                            "visible": true,
                        },

                        "title": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "title",
                            "visible": true,
                        },
                    },
                },
                "visible": true,
            },
        },
    },

    "input": {
        "fields": {
            "slug": "String!",
        },

        "types": {},

        "defaults": {},

        "runtimeScalars": {},
    },

    "pluginData": {},
    "policy": "CacheOrNetwork",
    "partial": false
} as const

export type Post$artifact = typeof artifact

/** Runtime handle for `Post`. This is what a `.gql` import or the generated barrel yields. */
export type Post = Artifact<'query', Post$result, Post$input, never>

export type Post$result = {
	readonly post: {
		readonly slug: string;
		readonly title: string;
		readonly description: string;
		readonly date: string;
		readonly tags: ReadonlyArray<string>;
		readonly blocks: ReadonlyArray<{
			readonly id: string;
			readonly kind: string;
			readonly depth: number;
			readonly html: string;
			readonly text: string;
			readonly noteIds: ReadonlyArray<string>;
			readonly image: string | null;
			readonly caption: string | null;
		}> | null;
		readonly notes: ReadonlyArray<{
			readonly id: string;
			readonly number: number;
			readonly html: string;
			readonly text: string;
		}> | null;
		readonly " $loadingFrame"?: undefined;
	} | null;
};

export type Post$input = {
	readonly slug: string;
};

export type Post$unmasked = {
	readonly post: {
		readonly __typename: "Post";
		readonly slug: string;
		readonly title: string;
		readonly description: string;
		readonly date: string;
		readonly tags: ReadonlyArray<string>;
		readonly blocks: ReadonlyArray<{
			readonly __typename: "Block";
			readonly id: string;
			readonly kind: string;
			readonly depth: number;
			readonly html: string;
			readonly text: string;
			readonly noteIds: ReadonlyArray<string>;
			readonly image: string | null;
			readonly caption: string | null;
		}> | null;
		readonly notes: ReadonlyArray<{
			readonly __typename: "Note";
			readonly id: string;
			readonly number: number;
			readonly html: string;
			readonly text: string;
		}> | null;
	} | null;
};

const document: Post = artifact as unknown as Post

export default document
