/** This file is automatically generated by Flamme. Do not edit. */
// source: .flamme/composed/Routeblog__slug__1gn4ng.composed.gql
import type { Artifact } from '@flamme/runtime'

const artifact = {
    "name": "Routeblog__slug__1gn4ng",
    "kind": "query",
    "hash": "a27e179cc9f0fb3378c82459b37ce91b90002f8c9c70f702187734ab3995f52f",
    "raw": `query Routeblog__slug__1gn4ng($slug: String!) {
    post(slug: $slug) {
        __typename
        blocks {
            __typename
            caption
            depth
            html
            id
            image
            kind
            noteIds
            text
        }
        date
        description
        notes {
            __typename
            html
            id
            number
            text
        }
        slug
        tags
        title
    }
    site {
        __typename
        date
        name
        tagline
    }
}
`,

    "rootType": "Query",
    "stripVariables": [] as Array<string>,

    "selection": {
        "fields": {
            "post": {
                "type": "Post",
                "modifiers": "Post",
                "keyRaw": "post(slug: $slug)",
                "nullable": true,

                "selection": {
                    "fields": {
                        "__typename": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "__typename",
                        },

                        "blocks": {
                            "type": "Block",
                            "modifiers": "[Block!]",
                            "keyRaw": "blocks",
                            "nullable": true,

                            "selection": {
                                "fields": {
                                    "__typename": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "__typename",
                                    },

                                    "caption": {
                                        "type": "String",
                                        "modifiers": "String",
                                        "keyRaw": "caption",
                                        "nullable": true,
                                        "visible": true,
                                    },

                                    "depth": {
                                        "type": "Int",
                                        "modifiers": "Int!",
                                        "keyRaw": "depth",
                                        "visible": true,
                                    },

                                    "html": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "html",
                                        "visible": true,
                                    },

                                    "id": {
                                        "type": "ID",
                                        "modifiers": "ID!",
                                        "keyRaw": "id",
                                        "visible": true,
                                    },

                                    "image": {
                                        "type": "String",
                                        "modifiers": "String",
                                        "keyRaw": "image",
                                        "nullable": true,
                                        "visible": true,
                                    },

                                    "kind": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "kind",
                                        "visible": true,
                                    },

                                    "noteIds": {
                                        "type": "String",
                                        "modifiers": "[String!]!",
                                        "keyRaw": "noteIds",
                                        "visible": true,
                                    },

                                    "text": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "text",
                                        "visible": true,
                                    },
                                },
                            },
                            "visible": true,
                        },

                        "date": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "date",
                            "visible": true,
                        },

                        "description": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "description",
                            "visible": true,
                        },

                        "notes": {
                            "type": "Note",
                            "modifiers": "[Note!]",
                            "keyRaw": "notes",
                            "nullable": true,

                            "selection": {
                                "fields": {
                                    "__typename": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "__typename",
                                    },

                                    "html": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "html",
                                        "visible": true,
                                    },

                                    "id": {
                                        "type": "ID",
                                        "modifiers": "ID!",
                                        "keyRaw": "id",
                                        "visible": true,
                                    },

                                    "number": {
                                        "type": "Int",
                                        "modifiers": "Int!",
                                        "keyRaw": "number",
                                        "visible": true,
                                    },

                                    "text": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "text",
                                        "visible": true,
                                    },
                                },
                            },
                            "visible": true,
                        },

                        "slug": {
                            "type": "ID",
                            "modifiers": "ID!",
                            "keyRaw": "slug",
                            "visible": true,
                        },

                        "tags": {
                            "type": "String",
                            "modifiers": "[String!]!",
                            "keyRaw": "tags",
                            "visible": true,
                        },

                        "title": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "title",
                            "visible": true,
                        },
                    },
                },
                "visible": true,
            },

            "site": {
                "type": "Site",
                "modifiers": "Site",
                "keyRaw": "site",
                "nullable": true,

                "selection": {
                    "fields": {
                        "__typename": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "__typename",
                        },

                        "date": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "date",
                            "visible": true,
                        },

                        "name": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "name",
                            "visible": true,
                        },

                        "tagline": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "tagline",
                            "visible": true,
                        },
                    },
                },
                "visible": true,
            },
        },
    },

    "input": {
        "fields": {
            "slug": "String!",
        },

        "types": {},

        "defaults": {},

        "runtimeScalars": {},
    },

    "pluginData": {},
    "policy": "CacheOrNetwork",
    "partial": false
} as const

export type Routeblog__slug__1gn4ng$artifact = typeof artifact

/** Runtime handle for `Routeblog__slug__1gn4ng`. This is what a `.gql` import or the generated barrel yields. */
export type Routeblog__slug__1gn4ng = Artifact<'query', Routeblog__slug__1gn4ng$result, Routeblog__slug__1gn4ng$input, never>

export type Routeblog__slug__1gn4ng$result = {
	readonly site: {
		readonly name: string;
		readonly tagline: string;
		readonly date: string;
		readonly " $loadingFrame"?: undefined;
	} | null;
	readonly post: {
		readonly slug: string;
		readonly title: string;
		readonly description: string;
		readonly date: string;
		readonly tags: ReadonlyArray<string>;
		readonly blocks: ReadonlyArray<{
			readonly id: string;
			readonly kind: string;
			readonly depth: number;
			readonly html: string;
			readonly text: string;
			readonly noteIds: ReadonlyArray<string>;
			readonly image: string | null;
			readonly caption: string | null;
		}> | null;
		readonly notes: ReadonlyArray<{
			readonly id: string;
			readonly number: number;
			readonly html: string;
			readonly text: string;
		}> | null;
		readonly " $loadingFrame"?: undefined;
	} | null;
};

export type Routeblog__slug__1gn4ng$input = {
	readonly slug: string;
};

export type Routeblog__slug__1gn4ng$unmasked = {
	readonly site: {
		readonly __typename: "Site";
		readonly name: string;
		readonly tagline: string;
		readonly date: string;
	} | null;
	readonly post: {
		readonly __typename: "Post";
		readonly slug: string;
		readonly title: string;
		readonly description: string;
		readonly date: string;
		readonly tags: ReadonlyArray<string>;
		readonly blocks: ReadonlyArray<{
			readonly __typename: "Block";
			readonly id: string;
			readonly kind: string;
			readonly depth: number;
			readonly html: string;
			readonly text: string;
			readonly noteIds: ReadonlyArray<string>;
			readonly image: string | null;
			readonly caption: string | null;
		}> | null;
		readonly notes: ReadonlyArray<{
			readonly __typename: "Note";
			readonly id: string;
			readonly number: number;
			readonly html: string;
			readonly text: string;
		}> | null;
	} | null;
};

const document: Routeblog__slug__1gn4ng = artifact as unknown as Routeblog__slug__1gn4ng

export default document
