/** This file is automatically generated by Flamme. Do not edit. */
// source: .flamme/composed/Routelibrary_n8fr6o.composed.gql
import type { Artifact } from '@flamme/runtime'

const artifact = {
    "name": "Routelibrary_n8fr6o",
    "kind": "query",
    "hash": "b697adc2f5d1fa980efe7568cf7d60eaa16cbbe4768bb36d8fd3099fdf74a9f7",
    "raw": `query Routelibrary_n8fr6o {
    shelves {
        __typename
        label
        repositories {
            __typename
            archived
            category
            description
            homepage
            language
            name
            stars
            url
        }
        slug
    }
    site {
        __typename
        date
        name
        tagline
    }
}
`,

    "rootType": "Query",
    "stripVariables": [] as Array<string>,

    "selection": {
        "fields": {
            "shelves": {
                "type": "Shelf",
                "modifiers": "[Shelf!]",
                "keyRaw": "shelves",
                "nullable": true,

                "selection": {
                    "fields": {
                        "__typename": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "__typename",
                        },

                        "label": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "label",
                            "visible": true,
                        },

                        "repositories": {
                            "type": "Repository",
                            "modifiers": "[Repository!]",
                            "keyRaw": "repositories",
                            "nullable": true,

                            "selection": {
                                "fields": {
                                    "__typename": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "__typename",
                                    },

                                    "archived": {
                                        "type": "Boolean",
                                        "modifiers": "Boolean!",
                                        "keyRaw": "archived",
                                        "visible": true,
                                    },

                                    "category": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "category",
                                        "visible": true,
                                    },

                                    "description": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "description",
                                        "visible": true,
                                    },

                                    "homepage": {
                                        "type": "String",
                                        "modifiers": "String",
                                        "keyRaw": "homepage",
                                        "nullable": true,
                                        "visible": true,
                                    },

                                    "language": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "language",
                                        "visible": true,
                                    },

                                    "name": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "name",
                                        "visible": true,
                                    },

                                    "stars": {
                                        "type": "Int",
                                        "modifiers": "Int",
                                        "keyRaw": "stars",
                                        "nullable": true,
                                        "visible": true,
                                    },

                                    "url": {
                                        "type": "String",
                                        "modifiers": "String!",
                                        "keyRaw": "url",
                                        "visible": true,
                                    },
                                },
                            },
                            "visible": true,
                        },

                        "slug": {
                            "type": "ID",
                            "modifiers": "ID!",
                            "keyRaw": "slug",
                            "visible": true,
                        },
                    },
                },
                "visible": true,
            },

            "site": {
                "type": "Site",
                "modifiers": "Site",
                "keyRaw": "site",
                "nullable": true,

                "selection": {
                    "fields": {
                        "__typename": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "__typename",
                        },

                        "date": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "date",
                            "visible": true,
                        },

                        "name": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "name",
                            "visible": true,
                        },

                        "tagline": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "tagline",
                            "visible": true,
                        },
                    },
                },
                "visible": true,
            },
        },
    },

    "input": {
        "fields": {},

        "types": {},

        "defaults": {},

        "runtimeScalars": {},
    },

    "pluginData": {},
    "policy": "CacheOrNetwork",
    "partial": false
} as const

export type Routelibrary_n8fr6o$artifact = typeof artifact

/** Runtime handle for `Routelibrary_n8fr6o`. This is what a `.gql` import or the generated barrel yields. */
export type Routelibrary_n8fr6o = Artifact<'query', Routelibrary_n8fr6o$result, Routelibrary_n8fr6o$input, never>

export type Routelibrary_n8fr6o$result = {
	readonly site: {
		readonly name: string;
		readonly tagline: string;
		readonly date: string;
		readonly " $loadingFrame"?: undefined;
	} | null;
	readonly shelves: ReadonlyArray<{
		readonly slug: string;
		readonly label: string;
		readonly repositories: ReadonlyArray<{
			readonly name: string;
			readonly description: string;
			readonly language: string;
			readonly url: string;
			readonly homepage: string | null;
			readonly archived: boolean;
			readonly category: string;
			readonly stars: number | null;
		}> | null;
		readonly " $loadingFrame"?: undefined;
	}> | null;
};

export type Routelibrary_n8fr6o$input = Record<string, never>;

export type Routelibrary_n8fr6o$unmasked = {
	readonly site: {
		readonly __typename: "Site";
		readonly name: string;
		readonly tagline: string;
		readonly date: string;
	} | null;
	readonly shelves: ReadonlyArray<{
		readonly __typename: "Shelf";
		readonly slug: string;
		readonly label: string;
		readonly repositories: ReadonlyArray<{
			readonly __typename: "Repository";
			readonly name: string;
			readonly description: string;
			readonly language: string;
			readonly url: string;
			readonly homepage: string | null;
			readonly archived: boolean;
			readonly category: string;
			readonly stars: number | null;
		}> | null;
	}> | null;
};

const document: Routelibrary_n8fr6o = artifact as unknown as Routelibrary_n8fr6o

export default document
