/** This file is automatically generated by Flamme. Do not edit. */
// source: .flamme/composed/Routeexperience_fpods0.composed.gql
import type { Artifact } from '@flamme/runtime'

const artifact = {
    "name": "Routeexperience_fpods0",
    "kind": "query",
    "hash": "b50e76ab0d03e69efc66a373622806f1630e004010941f683442fdb3621c1c49",
    "raw": `query Routeexperience_fpods0 {
    roles {
        __typename
        company
        end
        highlights
        id
        location
        stack
        start
        summary
        title
    }
    schools {
        __typename
        end
        id
        location
        qualification
        school
        start
        summary
    }
    site {
        __typename
        date
        name
        tagline
    }
}
`,

    "rootType": "Query",
    "stripVariables": [] as Array<string>,

    "selection": {
        "fields": {
            "roles": {
                "type": "Role",
                "modifiers": "[Role!]",
                "keyRaw": "roles",
                "nullable": true,

                "selection": {
                    "fields": {
                        "__typename": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "__typename",
                        },

                        "company": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "company",
                            "visible": true,
                        },

                        "end": {
                            "type": "String",
                            "modifiers": "String",
                            "keyRaw": "end",
                            "nullable": true,
                            "visible": true,
                        },

                        "highlights": {
                            "type": "String",
                            "modifiers": "[String!]!",
                            "keyRaw": "highlights",
                            "visible": true,
                        },

                        "id": {
                            "type": "ID",
                            "modifiers": "ID!",
                            "keyRaw": "id",
                            "visible": true,
                        },

                        "location": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "location",
                            "visible": true,
                        },

                        "stack": {
                            "type": "String",
                            "modifiers": "[String!]!",
                            "keyRaw": "stack",
                            "visible": true,
                        },

                        "start": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "start",
                            "visible": true,
                        },

                        "summary": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "summary",
                            "visible": true,
                        },

                        "title": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "title",
                            "visible": true,
                        },
                    },
                },
                "visible": true,
            },

            "schools": {
                "type": "School",
                "modifiers": "[School!]",
                "keyRaw": "schools",
                "nullable": true,

                "selection": {
                    "fields": {
                        "__typename": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "__typename",
                        },

                        "end": {
                            "type": "String",
                            "modifiers": "String",
                            "keyRaw": "end",
                            "nullable": true,
                            "visible": true,
                        },

                        "id": {
                            "type": "ID",
                            "modifiers": "ID!",
                            "keyRaw": "id",
                            "visible": true,
                        },

                        "location": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "location",
                            "visible": true,
                        },

                        "qualification": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "qualification",
                            "visible": true,
                        },

                        "school": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "school",
                            "visible": true,
                        },

                        "start": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "start",
                            "visible": true,
                        },

                        "summary": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "summary",
                            "visible": true,
                        },
                    },
                },
                "visible": true,
            },

            "site": {
                "type": "Site",
                "modifiers": "Site",
                "keyRaw": "site",
                "nullable": true,

                "selection": {
                    "fields": {
                        "__typename": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "__typename",
                        },

                        "date": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "date",
                            "visible": true,
                        },

                        "name": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "name",
                            "visible": true,
                        },

                        "tagline": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "tagline",
                            "visible": true,
                        },
                    },
                },
                "visible": true,
            },
        },
    },

    "input": {
        "fields": {},

        "types": {},

        "defaults": {},

        "runtimeScalars": {},
    },

    "pluginData": {},
    "policy": "CacheOrNetwork",
    "partial": false
} as const

export type Routeexperience_fpods0$artifact = typeof artifact

/** Runtime handle for `Routeexperience_fpods0`. This is what a `.gql` import or the generated barrel yields. */
export type Routeexperience_fpods0 = Artifact<'query', Routeexperience_fpods0$result, Routeexperience_fpods0$input, never>

export type Routeexperience_fpods0$result = {
	readonly site: {
		readonly name: string;
		readonly tagline: string;
		readonly date: string;
		readonly " $loadingFrame"?: undefined;
	} | null;
	readonly roles: ReadonlyArray<{
		readonly id: string;
		readonly title: string;
		readonly company: string;
		readonly location: string;
		readonly start: string;
		readonly end: string | null;
		readonly summary: string;
		readonly highlights: ReadonlyArray<string>;
		readonly stack: ReadonlyArray<string>;
		readonly " $loadingFrame"?: undefined;
	}> | null;
	readonly schools: ReadonlyArray<{
		readonly id: string;
		readonly qualification: string;
		readonly school: string;
		readonly location: string;
		readonly start: string;
		readonly end: string | null;
		readonly summary: string;
		readonly " $loadingFrame"?: undefined;
	}> | null;
};

export type Routeexperience_fpods0$input = Record<string, never>;

export type Routeexperience_fpods0$unmasked = {
	readonly site: {
		readonly __typename: "Site";
		readonly name: string;
		readonly tagline: string;
		readonly date: string;
	} | null;
	readonly roles: ReadonlyArray<{
		readonly __typename: "Role";
		readonly id: string;
		readonly title: string;
		readonly company: string;
		readonly location: string;
		readonly start: string;
		readonly end: string | null;
		readonly summary: string;
		readonly highlights: ReadonlyArray<string>;
		readonly stack: ReadonlyArray<string>;
	}> | null;
	readonly schools: ReadonlyArray<{
		readonly __typename: "School";
		readonly id: string;
		readonly qualification: string;
		readonly school: string;
		readonly location: string;
		readonly start: string;
		readonly end: string | null;
		readonly summary: string;
	}> | null;
};

const document: Routeexperience_fpods0 = artifact as unknown as Routeexperience_fpods0

export default document
