/** This file is automatically generated by Flamme. Do not edit. */
// source: .flamme/composed/Route_layout_oy84b0.composed.gql
import type { Artifact } from '@flamme/runtime'

const artifact = {
    "name": "Route_layout_oy84b0",
    "kind": "query",
    "hash": "89361335631b97168091314a8f37003ea04229c5b75da7afd40b6d45a9b1af74",
    "raw": `query Route_layout_oy84b0 {
    site {
        __typename
        date
        name
        tagline
    }
}
`,

    "rootType": "Query",
    "stripVariables": [] as Array<string>,

    "selection": {
        "fields": {
            "site": {
                "type": "Site",
                "modifiers": "Site",
                "keyRaw": "site",
                "nullable": true,

                "selection": {
                    "fields": {
                        "__typename": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "__typename",
                        },

                        "date": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "date",
                            "visible": true,
                        },

                        "name": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "name",
                            "visible": true,
                        },

                        "tagline": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "tagline",
                            "visible": true,
                        },
                    },
                },
                "visible": true,
            },
        },
    },

    "input": {
        "fields": {},

        "types": {},

        "defaults": {},

        "runtimeScalars": {},
    },

    "pluginData": {},
    "policy": "CacheOrNetwork",
    "partial": false
} as const

export type Route_layout_oy84b0$artifact = typeof artifact

/** Runtime handle for `Route_layout_oy84b0`. This is what a `.gql` import or the generated barrel yields. */
export type Route_layout_oy84b0 = Artifact<'query', Route_layout_oy84b0$result, Route_layout_oy84b0$input, never>

export type Route_layout_oy84b0$result = {
	readonly site: {
		readonly name: string;
		readonly tagline: string;
		readonly date: string;
		readonly " $loadingFrame"?: undefined;
	} | null;
};

export type Route_layout_oy84b0$input = Record<string, never>;

export type Route_layout_oy84b0$unmasked = {
	readonly site: {
		readonly __typename: "Site";
		readonly name: string;
		readonly tagline: string;
		readonly date: string;
	} | null;
};

const document: Route_layout_oy84b0 = artifact as unknown as Route_layout_oy84b0

export default document
