/** This file is automatically generated by Flamme. Do not edit. */
// source: .flamme/composed/Routeindex_1pcgrc.composed.gql
import type { Artifact } from '@flamme/runtime'

const artifact = {
    "name": "Routeindex_1pcgrc",
    "kind": "query",
    "hash": "6f472eb65236244016e5300af787fe3251a5bb5e7f7b775b47985113f42937b2",
    "raw": `query Routeindex_1pcgrc {
    site {
        __typename
        date
        name
        tagline
    }
}
`,

    "rootType": "Query",
    "stripVariables": [] as Array<string>,

    "selection": {
        "fields": {
            "site": {
                "type": "Site",
                "modifiers": "Site",
                "keyRaw": "site",
                "nullable": true,

                "selection": {
                    "fields": {
                        "__typename": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "__typename",
                        },

                        "date": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "date",
                            "visible": true,
                        },

                        "name": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "name",
                            "visible": true,
                        },

                        "tagline": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "tagline",
                            "visible": true,
                        },
                    },
                },
                "visible": true,
            },
        },
    },

    "input": {
        "fields": {},

        "types": {},

        "defaults": {},

        "runtimeScalars": {},
    },

    "pluginData": {},
    "policy": "CacheOrNetwork",
    "partial": false
} as const

export type Routeindex_1pcgrc$artifact = typeof artifact

/** Runtime handle for `Routeindex_1pcgrc`. This is what a `.gql` import or the generated barrel yields. */
export type Routeindex_1pcgrc = Artifact<'query', Routeindex_1pcgrc$result, Routeindex_1pcgrc$input, never>

export type Routeindex_1pcgrc$result = {
	readonly site: {
		readonly name: string;
		readonly tagline: string;
		readonly date: string;
		readonly " $loadingFrame"?: undefined;
	} | null;
};

export type Routeindex_1pcgrc$input = Record<string, never>;

export type Routeindex_1pcgrc$unmasked = {
	readonly site: {
		readonly __typename: "Site";
		readonly name: string;
		readonly tagline: string;
		readonly date: string;
	} | null;
};

const document: Routeindex_1pcgrc = artifact as unknown as Routeindex_1pcgrc

export default document
