/** This file is automatically generated by Flamme. Do not edit. */
// source: .flamme/composed/Routeblog_1j1hl4.composed.gql
import type { Artifact } from '@flamme/runtime'

const artifact = {
    "name": "Routeblog_1j1hl4",
    "kind": "query",
    "hash": "b6b6208106661e5850165b287aa3105e597c439ea8129688fd0dc499cc73b138",
    "raw": `query Routeblog_1j1hl4 {
    posts {
        __typename
        date
        description
        slug
        tags
        title
    }
    site {
        __typename
        date
        name
        tagline
    }
}
`,

    "rootType": "Query",
    "stripVariables": [] as Array<string>,

    "selection": {
        "fields": {
            "posts": {
                "type": "Post",
                "modifiers": "[Post!]",
                "keyRaw": "posts",
                "nullable": true,

                "selection": {
                    "fields": {
                        "__typename": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "__typename",
                        },

                        "date": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "date",
                            "visible": true,
                        },

                        "description": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "description",
                            "visible": true,
                        },

                        "slug": {
                            "type": "ID",
                            "modifiers": "ID!",
                            "keyRaw": "slug",
                            "visible": true,
                        },

                        "tags": {
                            "type": "String",
                            "modifiers": "[String!]!",
                            "keyRaw": "tags",
                            "visible": true,
                        },

                        "title": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "title",
                            "visible": true,
                        },
                    },
                },
                "visible": true,
            },

            "site": {
                "type": "Site",
                "modifiers": "Site",
                "keyRaw": "site",
                "nullable": true,

                "selection": {
                    "fields": {
                        "__typename": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "__typename",
                        },

                        "date": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "date",
                            "visible": true,
                        },

                        "name": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "name",
                            "visible": true,
                        },

                        "tagline": {
                            "type": "String",
                            "modifiers": "String!",
                            "keyRaw": "tagline",
                            "visible": true,
                        },
                    },
                },
                "visible": true,
            },
        },
    },

    "input": {
        "fields": {},

        "types": {},

        "defaults": {},

        "runtimeScalars": {},
    },

    "pluginData": {},
    "policy": "CacheOrNetwork",
    "partial": false
} as const

export type Routeblog_1j1hl4$artifact = typeof artifact

/** Runtime handle for `Routeblog_1j1hl4`. This is what a `.gql` import or the generated barrel yields. */
export type Routeblog_1j1hl4 = Artifact<'query', Routeblog_1j1hl4$result, Routeblog_1j1hl4$input, never>

export type Routeblog_1j1hl4$result = {
	readonly site: {
		readonly name: string;
		readonly tagline: string;
		readonly date: string;
		readonly " $loadingFrame"?: undefined;
	} | null;
	readonly posts: ReadonlyArray<{
		readonly slug: string;
		readonly title: string;
		readonly description: string;
		readonly date: string;
		readonly tags: ReadonlyArray<string>;
		readonly " $loadingFrame"?: undefined;
	}> | null;
};

export type Routeblog_1j1hl4$input = Record<string, never>;

export type Routeblog_1j1hl4$unmasked = {
	readonly site: {
		readonly __typename: "Site";
		readonly name: string;
		readonly tagline: string;
		readonly date: string;
	} | null;
	readonly posts: ReadonlyArray<{
		readonly __typename: "Post";
		readonly slug: string;
		readonly title: string;
		readonly description: string;
		readonly date: string;
		readonly tags: ReadonlyArray<string>;
	}> | null;
};

const document: Routeblog_1j1hl4 = artifact as unknown as Routeblog_1j1hl4

export default document
