/** This file is automatically generated by Flamme. Do not edit. */

declare module '*/Blog.gql' {
	const document: typeof import('./artifacts/Blog')['default']
	export default document
}

declare module '*/Blog.graphql' {
	const document: typeof import('./artifacts/Blog')['default']
	export default document
}

declare module '*/Chrome.gql' {
	const document: typeof import('./artifacts/Chrome')['default']
	export default document
}

declare module '*/Chrome.graphql' {
	const document: typeof import('./artifacts/Chrome')['default']
	export default document
}

declare module '*/Experience.gql' {
	const document: typeof import('./artifacts/Experience')['default']
	export default document
}

declare module '*/Experience.graphql' {
	const document: typeof import('./artifacts/Experience')['default']
	export default document
}

declare module '*/Home.gql' {
	const document: typeof import('./artifacts/Home')['default']
	export default document
}

declare module '*/Home.graphql' {
	const document: typeof import('./artifacts/Home')['default']
	export default document
}

declare module '*/Library.gql' {
	const document: typeof import('./artifacts/Library')['default']
	export default document
}

declare module '*/Library.graphql' {
	const document: typeof import('./artifacts/Library')['default']
	export default document
}

declare module '*/Post.gql' {
	const document: typeof import('./artifacts/Post')['default']
	export default document
}

declare module '*/Post.graphql' {
	const document: typeof import('./artifacts/Post')['default']
	export default document
}
