/** This file is automatically generated by Flamme. Do not edit. */
// Installs the generated route table into @flamme/router/auto. `createFlammeRouter()` imports
// this module dynamically; a build without a generated tree never loads it.

import { setGeneratedRoutes } from '@flamme/router/auto'
import { records } from '$flamme/routes'

setGeneratedRoutes(records)
