/** This file is automatically generated by Flamme. Do not edit. */

export * from './runtime/index'

export { default as Blog } from './artifacts/Blog'
export type { Blog$result, Blog$input, Blog$unmasked, Blog$artifact } from './artifacts/Blog'
export { default as Chrome } from './artifacts/Chrome'
export type { Chrome$result, Chrome$input, Chrome$unmasked, Chrome$artifact } from './artifacts/Chrome'
export { default as Experience } from './artifacts/Experience'
export type { Experience$result, Experience$input, Experience$unmasked, Experience$artifact } from './artifacts/Experience'
export { default as Home } from './artifacts/Home'
export type { Home$result, Home$input, Home$unmasked, Home$artifact } from './artifacts/Home'
export { default as Library } from './artifacts/Library'
export type { Library$result, Library$input, Library$unmasked, Library$artifact } from './artifacts/Library'
export { default as Post } from './artifacts/Post'
export type { Post$result, Post$input, Post$unmasked, Post$artifact } from './artifacts/Post'

/** Typed `graphql()`: a keyed lookup, not an overload table. */
export interface DocumentMap {
  "query Blog {\n\tsite {\n\t\tname\n\t\tdate\n\t}\n\tposts {\n\t\tslug\n\t\ttitle\n\t\tdescription\n\t\tdate\n\t\ttags\n\t}\n}\n": typeof import('./artifacts/Blog').default
  "query Chrome {\n\tsite {\n\t\tname\n\t\ttagline\n\t\tdate\n\t}\n}\n": typeof import('./artifacts/Chrome').default
  "query Experience {\n\troles {\n\t\tid\n\t\ttitle\n\t\tcompany\n\t\tlocation\n\t\tstart\n\t\tend\n\t\tsummary\n\t\thighlights\n\t\tstack\n\t}\n\tschools {\n\t\tid\n\t\tqualification\n\t\tschool\n\t\tlocation\n\t\tstart\n\t\tend\n\t\tsummary\n\t}\n}\n": typeof import('./artifacts/Experience').default
  "query Home {\n\tsite {\n\t\tname\n\t\ttagline\n\t\tdate\n\t}\n}\n": typeof import('./artifacts/Home').default
  "query Library {\n\tshelves {\n\t\tslug\n\t\tlabel\n\t\trepositories {\n\t\t\tname\n\t\t\tdescription\n\t\t\tlanguage\n\t\t\turl\n\t\t\thomepage\n\t\t\tarchived\n\t\t\tcategory\n\t\t\tstars\n\t\t}\n\t}\n}\n": typeof import('./artifacts/Library').default
  "query Post($slug: String!) {\n\tpost(slug: $slug) {\n\t\tslug\n\t\ttitle\n\t\tdescription\n\t\tdate\n\t\ttags\n\t\tblocks {\n\t\t\tid\n\t\t\tkind\n\t\t\tdepth\n\t\t\thtml\n\t\t\ttext\n\t\t\tnoteIds\n\t\t\timage\n\t\t\tcaption\n\t\t}\n\t\tnotes {\n\t\t\tid\n\t\t\tnumber\n\t\t\thtml\n\t\t\ttext\n\t\t}\n\t}\n}\n": typeof import('./artifacts/Post').default
}

/**
 * The `graphql()` fallback: the template text is not a key in `DocumentMap`.
 *
 * This type exists to be *named* in the error. A stale template (the document
 * was edited without running `flamme generate`) is the cause, so the fallback
 * type says so; a `never` fallback instead type-checked silently at the call
 * site and produced a misleading downstream error ("Property … does not exist
 * on type 'never'").
 */
export interface FLM_DocumentNotInGeneratedMap {
  readonly ' $documentNotInGeneratedMap': 'run `flamme generate`: this document text is not in DocumentMap'
}

export function graphql<T extends keyof DocumentMap>(source: T): DocumentMap[T]
export function graphql(source: string): FLM_DocumentNotInGeneratedMap
export function graphql(source: string): never {
  throw new Error(`graphql() must be compiled away: ${source.slice(0, 40)}`)
}
