/** This file is automatically generated by Flamme. Do not edit. */

/**
 * Runtime prop descriptors for this project's fragments, and the validators they carry.
 *
 * A type argument alone cannot carry a runtime validator: the SFC compiler (`@vue/compiler-sfc`, or
 * Vize) erases `defineProps<{ species: SpriteInfo$key }>()` without evaluating the type, so the
 * compiled component's only check is Vue's inferred `{ type: Object }`. That is a Vue compiler
 * property, not a Flamme limitation, and the same call is still type-checked by `vue-tsc`.
 *
 * These descriptors are the runtime-honest path: `defineProps(SpriteInfoProp)` runs the real
 * `validator` on every incoming value, while `Object as PropType<SpriteInfo$key>` keeps the
 * vue-tsc checking the type-only form had.
 *
 * A value validates when it is a non-null object whose ` $fragments` marker holds a
 * `{ parent, variables }` reference under the fragment's own name. That accepts a masked value read
 * from the cache and a loading frame (a frame keeps its references), and rejects `null`, a plain
 * object with the right field names, and a marker for a different fragment.
 *
 * Two directive cases are deliberate:
 *
 * - `@when`/`@when_not` on a spread never removes the reference: the read writes the marker whether
 *   or not the condition holds, and only the spread's *fields* are conditional. An excluded spread
 *   therefore still validates; the child read reports `partial: true` with the fields absent.
 * - `@mask_disable` writes no marker at all, because the spread is inlined as the parent's own
 *   fields. Such a value does not validate, and the generated `$key` type rejects it too: a child
 *   that wants the inlined data takes the parent's own type (`$unmasked`), not a `$key`.
 *
 * Only each fragment's own marker entry is required. The transitive entries its `$key` also names
 * are written by the same read into the same marker object, so re-checking them adds no signal.
 *
 * Queries get no descriptor: a query result carries no ` $fragments` marker, so a validator could
 * only repeat Vue's `Object` check. Spread a fragment in the query and hand the child that `$key`.
 */

// This project declares no fragments, so there are no prop descriptors to emit.
