/** This file is automatically generated by Flamme. Do not edit. */
// One typed `usePageQuery()` per **page** record that declares a loader (a route group
// counts: it is a page record). A page component imports its own through the plugin’s
// rewrite; `$flamme/records/<name>` addresses one directly. A layout record has no module:
// `usePageQuery()` skips layout records by contract.

export * from './routes'

export * as blog from './records/blog.js'
export * as blog__slug_ from './records/blog__slug_.js'
export * as experience from './records/experience.js'
export * as index from './records/index.js'
export * as library from './records/library.js'
