/** This file is automatically generated by Flamme. Do not edit. */
// The filesystem route table: one record per page (and per layout), with the loader each of
// their documents needs. Edit the pages under 'src/pages' instead.

import {
  createComposedPageLoader,
  createPageLoader,
  defineFlammeRoutes,
  type FlammeRoute,
  type PageData,
} from '@flamme/router/auto'
import DocBlog from '$flamme/artifacts/Blog'
import DocChrome from '$flamme/artifacts/Chrome'
import DocExperience from '$flamme/artifacts/Experience'
import DocHome from '$flamme/artifacts/Home'
import DocLibrary from '$flamme/artifacts/Library'
import DocPost from '$flamme/artifacts/Post'
import DocRoute_layout_oy84b0 from '$flamme/artifacts/Route_layout_oy84b0'
import DocRouteblog_1j1hl4 from '$flamme/artifacts/Routeblog_1j1hl4'
import DocRouteblog__slug__1gn4ng from '$flamme/artifacts/Routeblog__slug__1gn4ng'
import DocRouteexperience_fpods0 from '$flamme/artifacts/Routeexperience_fpods0'
import DocRouteindex_1pcgrc from '$flamme/artifacts/Routeindex_1pcgrc'
import DocRoutelibrary_n8fr6o from '$flamme/artifacts/Routelibrary_n8fr6o'

/**
 * The route records, flat: `defineFlammeRoutes` nests them from each record’s parent, and the
 * nested `routes` below is for a caller that installs vue-router directly. This is the table
 * `createFlammeRouter()` composes and installs (through the `$flamme/auto-routes` shim), and
 * what a caller that needs to reshape a record (a test swapping one page component in, a tool
 * listing the loaders) rebuilds from.
 */
export const records: readonly FlammeRoute[] = [
  {
    name: '+layout',
    path: '/',
    meta: { flamme: 'layout' },
    component: () => import('../src/pages/+layout.vue'),
    params: [],
    loaders: [
      {
        load: (client) => createComposedPageLoader(client, DocRoute_layout_oy84b0, [], ['Chrome']),
      },
    ],
    unattachedLoaders: [
      {
        load: (client) => createPageLoader(client, DocChrome, []),
      },
    ],
    composedChain: ['Chrome'],
  },
  {
    name: 'blog',
    path: '/blog',
    parent: '+layout',
    segment: 'blog',
    meta: { flamme: 'page' },
    component: () => import('../src/pages/blog.vue'),
    params: [],
    loaders: [
      {
        load: (client) => createComposedPageLoader(client, DocRouteblog_1j1hl4, [], ['Chrome', 'Blog']),
      },
    ],
    unattachedLoaders: [
      {
        load: (client) => createPageLoader(client, DocBlog, []),
      },
    ],
    composedChain: ['Chrome', 'Blog'],
  },
  {
    name: 'blog.[slug]',
    path: '/blog/:slug',
    parent: '+layout',
    segment: 'blog/:slug',
    meta: { flamme: 'page' },
    component: () => import('../src/pages/blog/[slug].vue'),
    params: ['slug'],
    loaders: [
      {
        load: (client) =>
          createComposedPageLoader(
            client,
            DocRouteblog__slug__1gn4ng,
            [{ variable: 'slug', param: 'slug', coercion: 'string' }],
            ['Chrome', 'Post'],
          ),
      },
    ],
    unattachedLoaders: [
      {
        load: (client) => createPageLoader(client, DocPost, [{ variable: 'slug', param: 'slug', coercion: 'string' }]),
      },
    ],
    composedChain: ['Chrome', 'Post'],
  },
  {
    name: 'experience',
    path: '/experience',
    parent: '+layout',
    segment: 'experience',
    meta: { flamme: 'page' },
    component: () => import('../src/pages/experience.vue'),
    params: [],
    loaders: [
      {
        load: (client) => createComposedPageLoader(client, DocRouteexperience_fpods0, [], ['Chrome', 'Experience']),
      },
    ],
    unattachedLoaders: [
      {
        load: (client) => createPageLoader(client, DocExperience, []),
      },
    ],
    composedChain: ['Chrome', 'Experience'],
  },
  {
    name: 'index',
    path: '/',
    parent: '+layout',
    segment: '',
    meta: { flamme: 'page' },
    component: () => import('../src/pages/index.vue'),
    params: [],
    loaders: [
      {
        load: (client) => createComposedPageLoader(client, DocRouteindex_1pcgrc, [], ['Chrome', 'Home']),
      },
    ],
    unattachedLoaders: [
      {
        load: (client) => createPageLoader(client, DocHome, []),
      },
    ],
    composedChain: ['Chrome', 'Home'],
  },
  {
    name: 'library',
    path: '/library',
    parent: '+layout',
    segment: 'library',
    meta: { flamme: 'page' },
    component: () => import('../src/pages/library.vue'),
    params: [],
    loaders: [
      {
        load: (client) => createComposedPageLoader(client, DocRoutelibrary_n8fr6o, [], ['Chrome', 'Library']),
      },
    ],
    unattachedLoaders: [
      {
        load: (client) => createPageLoader(client, DocLibrary, []),
      },
    ],
    composedChain: ['Chrome', 'Library'],
  },
]

/**
 * What the generator knew about each page: its file, its path, its params and the documents
 * its loader runs. Exported for typed links and for tests, never read by the router.
 */
export const pages = {
  '+layout': { file: 'src/pages/+layout.vue', path: '/', params: [], documents: ['Chrome'] },
  blog: { file: 'src/pages/blog.vue', path: '/blog', params: [], documents: ['Blog'] },
  'blog.[slug]': { file: 'src/pages/blog/[slug].vue', path: '/blog/:slug', params: ['slug'], documents: ['Post'] },
  experience: { file: 'src/pages/experience.vue', path: '/experience', params: [], documents: ['Experience'] },
  index: { file: 'src/pages/index.vue', path: '/', params: [], documents: ['Home'] },
  library: { file: 'src/pages/library.vue', path: '/library', params: [], documents: ['Library'] },
} as const

/**
 * Every page’s own query handle, keyed by route name.
 *
 * `createFlammeRouter` builds these loaders; the module re-creates them here only to name their
 * types. The casts are the one place the generator bridges "the record’s loader is what the page
 * declares" (a runtime invariant it guarantees by construction) to TypeScript, which cannot see
 * through vue-router’s merged `meta`. `usePageQuery()` reads the real one from the route.
 */
export const pageQueries = {
  '+layout': null as unknown as PageData<typeof DocChrome>,
  blog: null as unknown as PageData<typeof DocBlog>,
  'blog.[slug]': null as unknown as PageData<typeof DocPost>,
  experience: null as unknown as PageData<typeof DocExperience>,
  index: null as unknown as PageData<typeof DocHome>,
  library: null as unknown as PageData<typeof DocLibrary>,
} as const

declare module '@flamme/router/auto' {
  /**
   * The pages this app declares, as a type registry (REQ-1). `usePageQuery()` is typed against
   * `FlammeGeneratedRoutes[keyof FlammeGeneratedRoutes]`, so a page gets its own query’s data,
   * errors and pagination surface with no type argument at either end.
   *
   * This is a **module augmentation**, not a global one: the registry is declared (and
   * documented) by `@flamme/router/auto`, and this module is what fills it for this app.
   */
  interface FlammeGeneratedRoutes {
    readonly '+layout': PageData<typeof DocChrome>
    readonly blog: PageData<typeof DocBlog>
    readonly 'blog.[slug]': PageData<typeof DocPost>
    readonly experience: PageData<typeof DocExperience>
    readonly index: PageData<typeof DocHome>
    readonly library: PageData<typeof DocLibrary>
  }
}

/**
 * The generated route table, nested by `defineFlammeRoutes` and typed as vue-router records, for
 * a caller that installs vue-router directly. `createFlammeRouter()` installs the flat `records`
 * above instead (through the `$flamme/auto-routes` shim), because composition reads `parent`
 * links off the flat table.
 */
export const routes = defineFlammeRoutes(records)

export default routes
