/**
 * Derives the site palette from the five coolors anchors.
 *
 * Anchors: coolors.co/75f4f4-90e0f3-b8b3e9-d999b9-d17b88
 *
 * Art direction is terminal plus newspaper, so the anchors are NOT the theme's
 * background and text. A newspaper prints black ink on paper and a terminal is
 * light on black; both want a neutral spine. So this script produces two things:
 *
 *   1. A neutral ink/paper ramp, warm-tinted toward newsprint rather than blue.
 *   2. A ramp per anchor, used only for accents: rules, section marks, active
 *      states, links and the chart.
 *
 * Each accent ramp keeps its anchor's OKLCH hue while walking lightness and
 * chroma, clamping every step into sRGB. Only steps that clear WCAG against the
 * surface they sit on may carry text, and every pairing the UI relies on is
 * asserted below, so a bad colour fails the script rather than shipping.
 *
 * Run with: node scripts/derive-palette.mjs
 */
import { writeFile } from "node:fs/promises"
import Color from "colorjs.io"

/** The five anchors, straight from the coolors link. */
const anchors = {
	aqua: "#75F4F4",
	frost: "#90E0F3",
	peri: "#B8B3E9",
	pink: "#D999B9",
	rose: "#D17B88"
}

/** Anchors are pale by design, so their usable dark end comes from lightness. */
const steps = {
	100: 93,
	200: 86,
	300: 78,
	400: 68,
	500: 58,
	600: 48,
	700: 39,
	800: 30,
	900: 21,
	950: 13
}

/**
 * The neutral spine. Not an anchor: neutral hues at the extremes are what make
 * the page read as ink on paper rather than as a coloured application.
 */
const neutrals = {
	0: "#ffffff",
	50: "#f7f6f3",
	100: "#eceae5",
	200: "#dbd8d1",
	300: "#b8b4ab",
	400: "#8d897f",
	500: "#6a665e",
	600: "#4c4943",
	700: "#35322e",
	800: "#22201d",
	900: "#151412",
	950: "#0a0a09"
}

const toOklch = (hex) => new Color(hex).to("oklch")
const toHex = (color) => color.to("srgb").toString({ format: "hex" })

/** Peak chroma at a given lightness, so every step stays renderable in sRGB. */
const chromaCeiling = (lightness) => {
	const t = Math.abs(lightness - 62) / 62
	return 0.17 * (1 - t * t * 0.8)
}

const ramp = (hex) => {
	const base = toOklch(hex)
	const baseL = base.coords[0] * 100
	const baseC = base.coords[1]
	const hue = base.coords[2]

	const out = {}
	for (const [name, lightness] of Object.entries(steps)) {
		// Hold the anchor's chroma near its own lightness, ease off far from it.
		const distance = Math.abs(lightness - baseL) / 100
		let chroma = Math.min(baseC * (1 - distance * 0.7), chromaCeiling(lightness))

		let color = new Color("oklch", [lightness / 100, Math.max(chroma, 0), hue])
		while (!color.inGamut("srgb") && chroma > 0) {
			chroma -= 0.002
			color = new Color("oklch", [lightness / 100, Math.max(chroma, 0), hue])
		}

		out[name] = toHex(color)
	}
	return out
}

const srgbToLinear = (c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4)
const luminance = (hex) => {
	const [r, g, b] = new Color(hex).to("srgb").coords.map(srgbToLinear)
	return 0.2126 * r + 0.7152 * g + 0.0722 * b
}
const contrast = (a, b) => {
	const [x, y] = [luminance(a), luminance(b)].sort((m, n) => n - m)
	return (x + 0.05) / (y + 0.05)
}

const ramps = Object.fromEntries(Object.entries(anchors).map(([n, h]) => [n, ramp(h)]))

// Emit the derived values so the token config imports them instead of
// duplicating hex codes by hand.
await writeFile(
	new URL("../packages/astro/palette.generated.ts", import.meta.url),
	`// Generated by scripts/derive-palette.mjs. Do not edit by hand.
// Run \`node scripts/derive-palette.mjs\` after changing an anchor.

export const neutrals = ${JSON.stringify(neutrals, null, "\t")} as const

export const accents = ${JSON.stringify(ramps, null, "\t")} as const

export type AccentName = keyof typeof accents
export type NeutralStep = keyof typeof neutrals
`,
	"utf8"
)

console.log("anchors → OKLCH")
for (const [name, hex] of Object.entries(anchors)) {
	const c = toOklch(hex)
	console.log(
		`  ${name.padEnd(6)} ${hex}  L ${(c.coords[0] * 100).toFixed(1)}  C ${c.coords[1].toFixed(4)}  H ${c.coords[2].toFixed(1)}`
	)
}

console.log("\nneutral spine")
console.log(
	"  " +
		Object.entries(neutrals)
			.map(([k, v]) => `${k}:${v}`)
			.join(" ")
)

console.log("\naccent ramps")
for (const [name, scale] of Object.entries(ramps)) {
	console.log(
		`  ${name.padEnd(6)} ${Object.entries(scale)
			.map(([k, v]) => `${k}:${v}`)
			.join(" ")}`
	)
}

/**
 * Every foreground/background pairing the two themes use.
 *
 * Light prints dark ink on paper, dark is a terminal with light ink on black.
 * Accents clear 4.5 when they carry text, and 1.3 when they are a rule that
 * still has to be perceivable against its surface.
 */
const PAPER = neutrals[50]
const BLACK = neutrals[950]

const checks = [
	["light", "body", neutrals[900], PAPER, 4.5],
	["light", "muted", neutrals[600], PAPER, 4.5],
	["light", "faint", neutrals[500], PAPER, 3],
	["light", "rule", neutrals[300], PAPER, 1.3],
	["light", "rule-strong", neutrals[800], PAPER, 3],
	["light", "accent text", ramps.rose[700], PAPER, 4.5],
	["light", "link", ramps.frost[700], PAPER, 4.5],
	["light", "secondary", ramps.peri[700], PAPER, 4.5],
	["light", "tertiary", ramps.pink[700], PAPER, 4.5],
	["light", "inverse on accent", neutrals[0], ramps.rose[700], 4.5],
	["dark", "body", neutrals[50], BLACK, 4.5],
	["dark", "muted", neutrals[300], BLACK, 4.5],
	["dark", "faint", neutrals[400], BLACK, 3],
	["dark", "rule", neutrals[700], BLACK, 1.3],
	["dark", "rule-strong", neutrals[400], BLACK, 3],
	["dark", "accent text", ramps.aqua[300], BLACK, 4.5],
	["dark", "link", ramps.frost[200], BLACK, 4.5],
	["dark", "secondary", ramps.peri[200], BLACK, 4.5],
	["dark", "tertiary", ramps.pink[200], BLACK, 4.5],
	["dark", "inverse on accent", BLACK, ramps.aqua[300], 4.5]
]

console.log("\ncontrast gates")
let failures = 0
for (const [theme, label, fg, bg, min] of checks) {
	const r = contrast(fg, bg)
	const ok = r >= min
	if (!ok) failures += 1
	console.log(
		`  ${ok ? "pass" : "FAIL"}  ${theme.padEnd(5)} ${label.padEnd(18)} ${fg} on ${bg}  ${r.toFixed(2)} (needs ${min})`
	)
}

/**
 * Nabla's own palettes, read from the font's CPAL table. The display face is a
 * colour font, so its colour comes from `font-palette` rather than `color`.
 * Palette 0 is the yellow default; layout.css overrides it per theme.
 */
const nablaPalettes = {
	0: [
		"#ffd214",
		"#ff552d",
		"#ff9b00",
		"#ff9123",
		"#ffd214",
		"#ffeb6e",
		"#ffd214",
		"#ffeb6e",
		"#fffabe",
		"#ffffff"
	],
	3: [
		"#5a5a78",
		"#141432",
		"#464664",
		"#323250",
		"#5a5a78",
		"#787896",
		"#5a5a78",
		"#787896",
		"#9696b4",
		"#c8c8d2"
	],
	4: [
		"#c3c3e1",
		"#555573",
		"#8c8caa",
		"#8282a0",
		"#c3c3e1",
		"#d7d7f5",
		"#c3c3e1",
		"#d7d7f5",
		"#f5f5ff",
		"#ffffff"
	]
}
console.log("\nnabla palettes available (default is 0, the yellow one)")
for (const [index, colors] of Object.entries(nablaPalettes)) {
	console.log(`  ${index}: ${colors.join(" ")}`)
}

console.log(`\n${failures === 0 ? "all pairings pass" : `${failures} pairing(s) failed`}`)
process.exitCode = failures === 0 ? 0 : 1
