/** This file is automatically generated by Flamme. Do not edit. */

export type CachePolicy$options =
  | "CacheOrNetwork"
  | "NetworkOnly"
  | "CacheAndNetwork"
  | "CacheOnly"

export type DedupeMatchMode$options =
  | "variables"
  | "all"

export type PaginateMode$options =
  | "SinglePage"
  | "Infinite"
