/** This file is automatically generated by Flamme. Do not edit. */
// The typed `usePageQuery()` of the route record 'blog.[slug]'
// (src/pages/blog/[slug].vue, loading 'Post').
//
// import { usePageQuery } from '$flamme/records/blog__slug_'

import {
  usePageQuery as useRecordPageQuery,
  type PageData,
  type RouteQueryHandle,
  type UseRouteQueryOptions,
} from '@flamme/router/auto'
import type DocPost from '../artifacts/Post'

/** The data this record's loader produces (the 'Post' document). */
export type PageQueryData = PageData<typeof DocPost>

/**
 * This record's own page query: `usePageQuery()` from `@flamme/router/auto`, typed to
 * the document this record's loader runs. The runtime is the same call, so the loader still
 * comes from the record that renders the calling component; the type parameter is fixed here
 * and is deliberately not part of this function’s signature.
 */
export function usePageQuery(options?: UseRouteQueryOptions): RouteQueryHandle<PageQueryData> {
  return useRecordPageQuery<PageQueryData>(options)
}

export default usePageQuery
