/** This file is automatically generated by Flamme. Do not edit. */
// The typed `usePageQuery()` of the route record 'library'
// (src/pages/library.vue, loading 'Library').
//
// import { usePageQuery } from '$flamme/records/library'

import {
  usePageQuery as useRecordPageQuery,
  type PageData,
  type RouteQueryHandle,
  type UseRouteQueryOptions,
} from '@flamme/router/auto'
import type DocLibrary from '../artifacts/Library'

/** The data this record's loader produces (the 'Library' document). */
export type PageQueryData = PageData<typeof DocLibrary>

/**
 * This record's own page query: `usePageQuery()` from `@flamme/router/auto`, typed to
 * the document this record's loader runs. The runtime is the same call, so the loader still
 * comes from the record that renders the calling component; the type parameter is fixed here
 * and is deliberately not part of this function’s signature.
 */
export function usePageQuery(options?: UseRouteQueryOptions): RouteQueryHandle<PageQueryData> {
  return useRecordPageQuery<PageQueryData>(options)
}

export default usePageQuery
